### ISSUE TITLE
Table of contents w/ escape codes on openstax.org polish book

### ISSUE THREAD

**Issue by reedstrm** [openstax/os-webview#1053]
https://github.com/Connexions/webview/issues/1596

https://openstax.org/details/books/fizyka-dla-szk%C3%B3%C5%82-wy%C5%BCszych-polska#details
click on "Spis treści" (table of contents) has xml numeric escapes in it. We need to fix it, either by fetching a different bit, or encoding it differently in archive

**Comment by reedstrm** [comment]
![image](https://user-images.githubusercontent.com/253212/35883494-012ee5bc-0b4d-11e8-9ced-04ae4d8d67d5.png)

**Comment by reedstrm** [comment]
fixed via https://github.com/openstax/openstax-cms/pull/535

**Comment by meeragovindaraju** [comment]
@reedstrm Can this issue be closed?
