### ISSUE TITLE
Provide better insight into who we are

### ISSUE THREAD

**Issue by philschatz** [openstax/os-webview#1085]
In order to allow people to know who we are, it would be nice to improve the `/about` page.

Some suggestions:

1. **individual linking** : add support for including a `#` in the `/about` URL so people can link to a specific bio. This would allow people to include a link to their About Page from their Profile page on various services like Slack, Trello, GitHub, Google Docs, etc
    - Then, to find out who someone is, it takes 2 clicks: 1 click on their avatar to go to their Profile page on Slack/Trello/GitHub/etc, and then a 2nd click to go to openstax.org/about#philschatz
1. **alternate image** : add support for displaying an alternate image when hovering over a person. This would allow people to show what their avatar is in other services like Slack, GitHub, Trello, etc
1. **links to other services** : add support for linking to people's Profile on other services like GitHub, Trello, Google Docs (some people will likely have privacy concerns so this might need to be opt-in)

# Vote

Just to get a feel... which ideas do you think would be helpful? _(click on a bar below to vote)_

[![](https://api.gh-polls.com/poll/01C97BNPNQ1Z1BERY6QZKJV1KW/individual%20linking)](https://api.gh-polls.com/poll/01C97BNPNQ1Z1BERY6QZKJV1KW/individual%20linking/vote)
[![](https://api.gh-polls.com/poll/01C97BNPNQ1Z1BERY6QZKJV1KW/alternate%20image)](https://api.gh-polls.com/poll/01C97BNPNQ1Z1BERY6QZKJV1KW/alternate%20image/vote)
[![](https://api.gh-polls.com/poll/01C97BNPNQ1Z1BERY6QZKJV1KW/links%20to%20other%20services)](https://api.gh-polls.com/poll/01C97BNPNQ1Z1BERY6QZKJV1KW/links%20to%20other%20services/vote)
[![](https://api.gh-polls.com/poll/01C97BNPNQ1Z1BERY6QZKJV1KW/something%20else%20(comment%20below))](https://api.gh-polls.com/poll/01C97BNPNQ1Z1BERY6QZKJV1KW/something%20else%20(comment%20below)/vote)

**Comment by lwtchu** [comment]
something else: if u dunno someone maybe strike up a convo and learn :joy:

**Comment by lwtchu** [comment]
We had the who's who running for a while - they're backed up on a trello board. When we replace honey one day we can pick up the who's who again

**Comment by RoyEJohnson** [comment]
I think this is outdated, since the About page no longer has individual people. The Team page does, but only for a few.
