### ISSUE TITLE
Change Request: "Coming Soon" for Ancillaries

### ISSUE THREAD

**Issue by openstaxalina** [openstax/os-webview#1314]
# Description

We want users to be able to see what ancillaries are in development and coming soon for their textbook. This will cut down on requests to Customer Support and Editorial. 

# Acceptance Criteria
- A field is added to the specific book page in the CMS
- If the field is filled out, the FE adds a description (provided by marcom) and coming soon banner to the resource. 
- A user can upload a sample or draft file if available.

**Comment by mwharrison** [comment]
@RoyEJohnson, either you or I can move this back to 1C after it's merged for the FE portion.
 This can't be merged until the TOC PR is merged, so it'd be helpful if you let me know when it's safe to remove that from the BE.

**Comment by RoyEJohnson** [comment]
@mwharrison 
The FE is pulling table of contents info from archive, so it is* safe to remove it from book detail info.

*should be

**Comment by Brooke-Fail** [comment]
Difficult to verify without the FE, but this is a BE code that users won't see, so it is fine to go out for the 10-23 release.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
