### ISSUE TITLE
Unnumbered EOC Sections Are Numbered in ToC on Book Page

### ISSUE THREAD

**Issue by openstaxalina** [openstax/os-webview#1340]
All the Assignable Webview books (see this list [here](https://docs.google.com/spreadsheets/d/1dVpPsE2wTIZyoC4n8GnooqpntC2IZDTjcSdNMPycfB0/edit#gid=233364321)) have unnumbered end of section chapters.  The sections are not numbered on CNX or in the PDF.  However, they are numbered in the ToC pulled into the book page:
![eobsectionsopenstaxorg](https://user-images.githubusercontent.com/7863733/52814175-1c85c300-3061-11e9-990a-940d2b7661ee.png)

I seem to recall that this problem was already fixed (?).  Is there a flag or similar that we need to select in the CMS?  cc: @allisonhowell @mwharrison

**Comment by openstaxalina** [comment]
Whoops, URL would be helpful: https://openstax.org/details/books/principles-managerial-accounting

**Comment by openstaxalina** [comment]
These should be able to be identified by data-type="composite-page".  Hélène, BrittanyJ, or Thomas could provide more information if needed.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Issue is still occurring.
<img width="1369" alt="Screen Shot 2019-10-04 at 2 17 46 PM" src="https://user-images.githubusercontent.com/48449285/66234166-959a5f00-e6b2-11e9-8716-29b9d49c742a.png">

**Comment by Brooke-Fail** [comment]
Verified in Production.
