### ISSUE TITLE
CC-BY-NC-SA Blurb Cuts Off on Book Page

### ISSUE THREAD

**Issue by openstaxalina** [openstax/os-webview#1341]
Please see screenshot for details:
![ccbyncsablurbopenstaxorg](https://user-images.githubusercontent.com/7863733/52814824-b732d180-3062-11e9-9856-87ebf9b9a795.png)

This was tested in **Chrome.**

**Comment by openstaxalina** [comment]
Whoops, URL would be helpful: https://openstax.org/details/books/principles-managerial-accounting

**Comment by RoyEJohnson** [comment]
The text is cut off in the data sent from the CMS. I don't know whether it's being truncated by the API or whether the data is actually short in the database. @mwharrison @allisonhowell 

See https://openstax.org/apps/cms/api/v2/pages/303/ and look for `license_text`

**Comment by RoyEJohnson** [comment]
I checked with Michael. The content of the field is truncated in the CMS. The field itself has plenty of capacity for more, and Michael even added to it to demonstrate.
CMS now:
https://openstax.org/apps/cms/api/v2/pages/292/
And in the FE:
https://openstax.org/details/books/principles-managerial-accounting
![image.png](https://images.zenhubusercontent.com/5bacf5c2179f09585770fba9/922fe9a1-def8-479b-af10-197f5aa17532)

**Comment by mwharrison** [comment]
Someone in marketing/books should review what I put in there too - I created that OTF!
