### ISSUE TITLE
500 error page

### ISSUE THREAD

**Issue by kjdav** [openstax/os-webview#1384]
### Description
When OSweb is behind Cloudfront, there is a possibility that users could encounter 500 errors. We want to show those users nice looking error messages and it would be ideal if those errors could be reported for developers to review.

BIT can do this work anytime after we put OSweb behind Cloudfront, but it's not a required dependency for REX to launch.

### Acceptance Criteria
- Create 500 page rendered by osweb when there are 500s
- 5xx errors should match what REX is building, for consistency (Dani reviewed the copy and prototypes)
- Errors are reported somewhere (REX is reporting to Sentry, when you work on this can check with us) 

Design:
H1: Uh-oh, there's been a glitch. 
H2: We're not quite sure what went wrong. You can go back, or visit <link>OpenStax Support</link> for help.
Prototype: https://drive.google.com/open?id=1o-MWsBVlnw2p3J9H1E9mXVOWLIBLp8Rn

**Comment by mwharrison** [comment]
@jpslav - when do you think a user would see the 500 errors? Normally 500 errors are from the backend, which the user doesn't hit directly.

**Comment by jpslav** [comment]
What kind of 500s have y'all hit in recent memory and how has it impacted the user experience?

**Comment by mwharrison** [comment]
@jpslav - the only 500s I can think of are when something happens on the backend that throws a 500, which might break a portion of the page. It usually doesn't take down the entire page - but is that what we want to do?
@RoyEJohnson might have a different recollection.

**Comment by RoyEJohnson** [comment]
That sounds right to me. I have notified Michael that the back end was returning 500s, but the FE has not done so. From the user's perspective, what generally happens is that a content area would get stuck in the Loading screen or otherwise fail to populate.
