### ISSUE TITLE
Refactor map pages

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1436]
The map pages should be refactored to use the framework more rather than manipulating the DOM programmatically.
They should also have tests written.

**Comment by victoria-cooke** [comment]
Followed up with @allisonhowell on this. She is handling review for the initial version of the map since she has already overseen the build with the original specs and requirements. UX will review the map after the release to make improvement recommendations for an updated version.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
