### ISSUE TITLE
Report request: Number of adoptions at multi-campus systems

### ISSUE THREAD

**Issue by nicolefinkbeiner** [openstax/os-webview#1437]
Hello!

Can you please help me figure out how many adoptions we have for higher education (four-year universities and community colleges only) that are at schools where there is a parent organization? Just the United States.

If we could list the adoptions, especially by school name and parent org, that would be especially helpful.

Thank you!
Nicole

**Comment by chouston31** [comment]
@nicolefinkbeiner https://na132.lightning.force.com/lightning/r/Report/00O4P000004hoX3UAI/view
