### ISSUE TITLE
Hero Journey page needs fixed and "turned off"

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1439]
The Hero Journey campaign is not currently running. We should have a placeholder page to inform people of that.

Testimonial submission is broken.
The login link is also broken (routes to "no page here").

Video for testimonial submission:
https://drive.google.com/file/d/15DDt-CPVO8Z0W2Rnosyiiz3-vsZ-908h/view?usp=sharing

Video for login:
https://drive.google.com/file/d/1mK-_Xtzz58sOuzvto9q4P82CKo8fgUu9/view?usp=sharing

**Comment by allisonhowell** [comment]
@RoyEJohnson Here is the text:

This page is turned off for now, but you can still become a OpenStax hero! Head to our subject page to explore our books. Then, when you're ready, fill out our adoption form to let us know that you've decided to try our book in your class!"

**Comment by Brooke-Fail** [comment]
Verified in QA. 
 
Safari seems to take a second or two longer to load if the adoption form link is clicked from the hero-page compared to Chrome and Firefox.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
