### ISSUE TITLE
Look into Import/Export Issues of Accounting Pages from Production into Dev

### ISSUE THREAD

**Issue by LilyJCao** [openstax/os-webview#1447]
Description

When Lily tries to import the Principles of Accounting (Volume 1 AND Volume 2) files (json/zip) into dev, she gets an error page that looks like attached file. Look into why this is happening and notify her of when the issue is fixed.

Acceptance Criteria

1. Look into why the error page is showing up. 
2. Fix the issue or notify Lily of how she can fix the issue.
3. Inform Lily of when problem is resolved.![Dev Error with Importing Accounting Page Files.PNG](https://images.zenhubusercontent.com/5ce41f9b09deb07373484668/810458b6-6971-4c08-b505-fea8c98b8889)

**Comment by berkalpyakici** [comment]
@LilyJCao, you tried to upload a compressed zip archive right?

**Comment by LilyJCao** [comment]
@berkalpyakici yeah

**Comment by Brooke-Fail** [comment]
This will be verified when it is pushed to Production.

**Comment by Brooke-Fail** [comment]
Verified on Production.
