### ISSUE TITLE
Resize book banners to align with REX

### ISSUE THREAD

**Issue by kjdav** [openstax/os-webview#1453]
Now that are getting closer to launching REX, it is time to schedule the work to resize the book banners. 

Acceptance: 
- Provide banner specs for desktop (done; see prototype - https://projects.invisionapp.com/d/main/default/#/console/16565650/344800862/preview) 
- Provide banner specs for mobile (needs to be done) 
- Resize banners for desktop screens 
- Resize banners for mobile screens

Link to prototype: https://projects.invisionapp.com/d/main/default/#/console/16565650/344800862/preview

**Comment by allisonhowell** [comment]
@victoria-cooke Is this good to pass to @RoyEJohnson

**Comment by victoria-cooke** [comment]
@allisonhowell I think so. @dkhowala Mentioned that she had already done the work for this. Devika, can you confirm?

**Comment by dkhowala** [comment]
Here are the specs for the desktop. https://projects.invisionapp.com/d/main?origin=v7#/console/16782796/368422153/preview

Have done the resizing for mobile too, have to check if the specs are done or not.

**Comment by victoria-cooke** [comment]
> https://projects.invisionapp.com/d/main?origin=v7#/console/16782796/368422153/preview

@dkhowala It says that I don't have permission to view.

**Comment by dkhowala** [comment]
@victoria-cooke You should be able to access it now. The specs for mobile are also included.

**Comment by victoria-cooke** [comment]
Thanks, @dkhowala. @allisonhowell This should be ready for @royejohnson to start working on. Regarding the SVGs used for the banner text, I do think we should convert those to text at some point. If Roy says he's comfortable with resizing the SVGs to fit the new banners, I think that works for now, though.

**Comment by RoyEJohnson** [comment]
Using SVGs allows the content side people to make each title look as it should. There is no way to specify a text-styling rule for the front end that will work across all titles, because they have per-title font color and size changes, as well as desired break positions. It could be done with a block of HTML that included styling for all its elements, but I don't see how that's preferable to SVGs.

I have made the header the proper height at desktop and mobile sizes (and chose a mid-size for tablet sizes) and the SVG will be sized to fill that height. SVGs can be retooled as needed to have the desired sizing and positioning.

**Comment by victoria-cooke** [comment]
@RoyEJohnson No problem. When it was mentioned REX was using plaintext for their titles, I mistakenly thought they had figured out a styling system for the titles as displayed on OS Web. These titles aren't used in their library though. I'm fine with using SVGs for what we have in place now.

**Comment by victoria-cooke** [comment]
@RoyEJohnson Review items can be found under the Book Banners label at https://trello.com/b/Vr2DfPT7/ux-review-openstax-logo-rover-page-book-banners.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Code on production has been verified.

**Comment by victoria-cooke** [comment]
@RoyEJohnson I'm not sure about the deep green gradient since the _Chemistry: Atoms First_ book won't open on dev. However, it looks like the rest of the gradients came through ok.

**Comment by victoria-cooke** [comment]
@RoyEJohnson Ok, just took a look at Chem. Looks good! This is ready to move on.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
