### ISSUE TITLE
Add padding to top and bottom of Table of Contents so it doesn't look like it scrolls under header and footer

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1456]
This is a final UX fix on the ToC that didn't get done for the previous release.

**Comment by victoria-cooke** [comment]
@RoyEJohnson Putting a note here about the additional fix I posted in Trello: https://trello.com/c/uW6WKASZ/49-partner-resources-tab-content-extends-beyond-page-boundary-when-toc-is-open

**Comment by RoyEJohnson** [comment]
@victoria-cooke The latest version on dev fixes the page boundary issue as well as the "switching to a tab with longer content" issue.

**Comment by victoria-cooke** [comment]
@RoyEJohnson I think these fixes are good to go. There are some things I would still like to update, but that will have to wait for a bit. Everything seems to be working as it should.

**Comment by itsgeraldwang** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging

**Comment by ejp3** [comment]
Verified in Production
