### ISSUE TITLE
Fix the Capitalization of the Partner resources Tab on Books Pages

### ISSUE THREAD

**Issue by LilyJCao** [openstax/os-webview#1464]
Description
Fix the capitalization of the "Partner Resources" tab to "Partner resources" on Books pages to match the capitalization of other tabs on the Books pages.

Acceptance
When the user navigates to the Books page for each subject, the partner resources tab is labeled "Partner resources" instead of "Partner Resources". 
Each partner resources tab on each Books page is labeled "Partner resources".

**Comment by itsgeraldwang** [comment]
Verified in QA.

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
