### ISSUE TITLE
Build partner portal for lead sharing with OpenStax Allies (Partners Upload Reports Directly into Portal)

### ISSUE THREAD

**Issue by LilyJCao** [openstax/os-webview#1472]
Description
We need to automate lead sharing with our partners so that we can send them better leads, faster. Right now we manually send over the reports as we have time, which is not an efficient way to deliver leads, and results in lost sales. Building an automated process using Salesforce's Community Cloud will solve this problem.

Acceptance Criteria
Partners can upload their adoption reports and lead reports directly into the partner portal and an email is sent to Courtney and/or marketing team member alerting them that it's been uploaded.

Checklist for Done
1A-DEFINE

 Description is complete
 High-level natural language acceptance tests are complete
 If UX design is needed then the UX label is added
 If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
 A high-level solution (development approach for the code change) is added to the issue
 If prototype code is generated, it is linked to the issue.
 If tech briefs are generated, they are linked to the issue.
1B-DECOMP

 The work is broken into reasonable and consistent work items.
 Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
 The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
 The story epic and child work item issues are moved into 1B-DECOMP DONE.
 If an issue is included in a product phase, then Release is selected.
1C-DESIGN

 The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
 Distilled acceptance tests are added to the issue.
 Automated testing criteria are added to issue.
 The solution is updated.
2-CODE

 A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
 The acceptance tests are finalized in "Given / When / Then" format.
 Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
4A-UX REVIEW

 The pull request is merged into master, and the change branch is deleted.
5A-FUNCT VER

 All the acceptance tests for this issue pass.
5C-REGRESSION

 The test plan in testrail passes.
 Blessing from Product Manager that the release is good to go.
5D-READY TO BE DEPLOYED

 Production is updated and verified.
 All issues in the release are closed.
QA needs checklist:

 Acceptance Criteria are complete
 Milestone should be tagged for PR's
 Milestone should be tagged for issues
 Content update needed
 Content update complete
Deployment needs

 Pre-deployment tasks
 Data migrations
 Post-deployment tasks
If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end

TRACK / EPICS

 All child issues are moved to 3B-RELEASE REVIEW.
3B-RELEASE REVIEW

 Acceptance tests pass for all issues in the release
 Blessing from Product Manager that the release is good to go.
3C-RELEASED

 Production is updated and verified.
 All issues in the release are closed.

**Comment by mwharrison** [comment]
Issue moved to [openstax/business-intel #451](https://github.com/openstax/business-intel/issues/451) via [**ZenHub**](https://www.zenhub.com/)
