### ISSUE TITLE
Change request: Changes to Student Answer Guide containers for 3 dev math books

### ISSUE THREAD

**Issue by kjdav** [openstax/os-webview#1492]
We want to test locking the student answer guides to drive login, but first we need to make a change to the answer guide containers for the 3 Dev math books. The reason is that we do NOT want to lock the student answer guides for the 3 dev math books. 

#Acceptance Criteria
- For prealgebra, create a new container in the Student Resources section called Answers to Selected Problems
- For prealgebra, move the Student Answer Guide into the Answers to Selected Problems container
- For Prealgebra, make sure the new Answers to Selected Problems container is unlocked (does not require login) 
- For Prealgebra, remove the now empty Student Answer Guide
- Complete all the steps above for both Elementary Algebra and Intermediate Algebra
- All 3 of the dev math books should have an unlocked container called Answers to Selected Problems and no container called Student Answer Guides

**Comment by allisonhowell** [comment]
Added to production 8/2/19.
