### ISSUE TITLE
Include Rover image on mobile popup

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1513]
This was in the original design but did not make it into the release.
Design is (still) at https://zpl.io/aRzGp7K

The reason it wasn't included in the release is that it would have required BE change to add an image asset. The one used for the desktop popup is cropped differently.

**Comment by RoyEJohnson** [comment]
I figured out how to do it with one image.

**Comment by victoria-cooke** [comment]
@RoyEJohnson It looks like the change for this didn't push through. Same issue with [#391](https://app.zenhub.com/workspaces/openstax-bit-5bacfe3f4b5806bc2bea3764/issues/openstax/business-intel/391).

**Comment by victoria-cooke** [comment]
@RoyEJohnson This is good to go

**Comment by Brooke-Fail** [comment]
The image is on the popup on the mobile view. There are a lot of other bugs with this page in mobile view. Since the new pages is still a WIP, so for the purpose of jut verifying the image on mobile, this passes in QA.

**Comment by Brooke-Fail** [comment]
Same as the previous comment, passed in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production, previous comments about mobile issues still apply.
