### ISSUE TITLE
Fix blog search issues

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1522]
- Search string is encoded in the location bar and needs to be decoded when copied to the search input.
 - Article dates are coming in as "undefined". Not passed?
 - Remove "Read more great stories"
 - Change article date format(?)
 - On phone, article summary layout should be picture-over-text, not side-by-side

# Testing
There is a separate card for the date in the byline, as it requires back-end work.
1. Search for a phrase like "just textbooks". Notice that the search bar is populated with it on the search results page, and that it is not encoded with `%3e` type characters.
2. "Read more great stories" no longer appears above the search bar.
3. On phone, search result article summary should be picture-on-top, text-below, rather than side-by-side.
4. Dates should display like July 1, 2019 rather than 2019-07-01 (this is corrected in search results as well as More Stories)

**Comment by Brooke-Fail** [comment]
Blog is not going out for 8/28 release, this is currently hidden.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
