### ISSUE TITLE
Book details/REX connections

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1542]
- TOC in staging is pulled from production; would be better to pull from staging
- Webview link looks internal but should act like external link (but open in current window)
- ~Do we have a way to pull the REX TOC? (Check with Tom)~

## Notes
TOC comes in the book info from the CMS. The FE builds each chapter link from the `webviewLink`, adding a `shortId` item from the TOC data. **This will likely require some reprogramming when the TOC is REX data.**

### Testing
This should only affect books with REX links. TOC links should open in the current window for those.

**Comment by Brooke-Fail** [comment]
Will verify in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Staging. Rex link works for view online (when inputted in the cms).

**Comment by Brooke-Fail** [comment]
We are not ready to change the view online links yet so I can not test this in production. Closing since prior testing has passed.
