### ISSUE TITLE
Contact form submit is broken

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1573]
Submitting the Contact form opens a new tab that loads the Contact form.
Submitting from the new tab reloads the Contact form in that tab.

Proper behavior is to load the Contact confirmation page in the same tab as the form was submitted from.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
