### ISSUE TITLE
Carousel arrows look misaligned

### ISSUE THREAD

**Issue by tomjw64** [openstax/os-webview#1592]
I love the new carousel on the openstax.org site that shows off the cool new map and OpenStax w/ SE apps!
While I was browsing I noticed the arrows in the carousel looked off-center. It seemed like adding the `align-items: center` rule to `.right-arrow, .left-arrow` in [banner-carousel.scss](https://github.com/openstax/os-webview/blob/master/src/app/pages/home/banner-carousel/banner-carousel.scss) would take care of the alignment.
![ox-arrows](https://user-images.githubusercontent.com/1285308/67221781-aa386000-f3f1-11e9-9196-1c2242f5c4c5.png)

**Comment by victoria-cooke** [comment]
@RoyEJohnson This is good to go

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
