### ISSUE TITLE
Rex links in Table of Contents should be based on rex webview link

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1594]
# Description
ToC links to Rex pages are based on production Rex. They should be based on the `rex_webview_link` provided by the CMS, which will make more sense for QA.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
