### ISSUE TITLE
Move coming soon banner on resources to the bottom so the title is not obscured

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1603]
The banner obscures the title. Moving it to the bottom of the resource box will obscure the download link, but that isn't operational on coming-soon resource boxes.

## Testing
I made a coming soon resource on the Prealgebra book

**Comment by RoyEJohnson** [comment]
@allisonhowell For your review. You can check the Prealgebra book in dev.

**Comment by allisonhowell** [comment]
@RoyEJohnson Perfect!

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
This is live and passed staging testing, closing.
