### ISSUE TITLE
Change request: "Recommended" callout behavior when we release highlighting and note taking for books

### ISSUE THREAD

**Issue by kjdav** [openstax/os-webview#1604]
We are targeting a Jan 15 release for highlighting. This may change, but I will keep Allison up to date. One thing that we want is to coordinate the highlighting/note taking release with an update to the Recommended callout on the book details page.

When we release highlighting and note taking for a book, we want: 

- On every book that has highlighting, every user should see the Recommended callout with verbiage that highlighting and note taking is available for the book
- Users who previously dismissed the Recommended callout should see it again, with the highlighting/note taking verbiage
- Users who previously saw the Recommended callout 3x should see it again 
- Users should see the "new" Recommended callout with highlighting/note taking verbiage 3x before it goes away

After Jan 15, 2020, all the callouts need to be reset.

# Testing

Because of the Jan 15 effective date, it cannot be tested now. As of Jan 15, all books on Rex will have highlighting and notetaking, and should show a callout, even if the callout was previously dismissed.

**Comment by kjdav** [comment]
Allison -- this is a card for the new "recommended" callout behavior. I think we discussed this could be accomplished by deleting the cookie that tracks whether users have seen it before January, but please talk to Michael and let me know. 

Also can you remind me how does the Recommended verbiage get set? Is it something we will do per book manually in the CMS?

**Comment by allisonhowell** [comment]
Thanks @kjdav. We'll let you know what we need to do here. The verbiage for the callout can all be set in the CMS. And yes, we'll do it per book.

**Comment by allisonhowell** [comment]
@RoyEJohnson This needs to be in the Jan 15 release. Can you get to it when you have a stopping point on thee marketplace?

**Comment by kjdav** [comment]
Discussed with Allison that we are not going to make the 1/15 release and we are targeting the 1/29 release. Allison is talking to Roy and Brooke about next steps. Thanks so much.

**Comment by Brooke-Fail** [comment]
Roy changed the date in the code (I can see the change in the PR). This code is going out in the 12/18 release, but I can not very on the users end or in the html until 1/29/2020.
cc @allisonhowell
