### ISSUE TITLE
OSweb query what version of the book is in REX and use that version to render the ToC

### ISSUE THREAD

**Issue by kjdav** [openstax/os-webview#1614]
Last week, CE styles changed the REX URL's and that had unintended consequences on REX and the ToC on the book details pages:  

• `Chapter` and `appendix` were added to the AP Biology recipe to support PDF styles.
• As a result, the chapter introduction, end-of-chapter, and appendix URLs in AP Biology changed.
• Since osweb uses the latest version, this led the AP Bio ToC on production osweb to have 404'ing links for the changed URLS. (This broke only on REX staging since our version is pinned.)

Going forward, it would be better/less brittle for OSweb to query what version of the book is in REX and use _that_ version to render the ToC on all book details pages.

Priority: this change is blocking CE styles from reapplying the styles we reverted. 
Out of scope: this doesn't imply any changes to the look of the ToC on the book details page. 

#Acceptance tests

Given the book details page on osweb for a REX book, e.g., https://openstax.org/details/books/chemistry-2e
And the book page ToC links are pointing directly to REX (not to CNX)
When a new version of the book is pushed to archive
And there is no corresponding REX update to use the latest version
Then the page titles/URLs for the book page ToC are not impacted
And the page titles/URLs in the book page ToC continue to match the page titles and URLS in the version of REX that is on production

Given the book details page on osweb for a REX book, e.g., https://openstax.org/details/books/chemistry-2e
And the ToC links are pointing directly to REX (not to CNX)
When REX gets an updated version of the content
Then the page titles/URLs for the book page ToC renders the page titles and URLs in the version of REX that is on production

**Comment by RoyEJohnson** [comment]
Talked with Kim about this a little, and neither of us had a complete understanding of what needs to happen. She suggested I talk with @TomWoodward when available.

**Comment by kjdav** [comment]
Added draft acceptance tests and a note that changes to the look of the ToC are out of scope, per discussion with Roy.

**Comment by Brooke-Fail** [comment]
Verified that the code going out in the 1/15 release is good.
