### ISSUE TITLE
Automate NPS Email from CS

### ISSUE THREAD

**Issue by njv2** [openstax/os-webview#1653]
For Denver or Chris: 
- Please set up Net Promoter Score email to send automatically after a case has been closed, but it was not initiated by someone in OpenStax (must have been created by someone externally). 
- Wait 1 day after case has been closed to send email 
- NPS email has already been created in Pardot 
- Let me know if you have any questions. - Nima V.

**Comment by denvergreene** [comment]
This card was made in the wrong little stupid category thing and couldn't have the right labels made to it and I couldn't edit it because of course I can't so I closed this one and made a new one
