### ISSUE TITLE
Fixes for February 12 release

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1659]
- [x] Fix bug with partners that have no books breaking the instructor resources
- [x] Remove Costs as separate filter; include in Advanced Filters
- [x] Remove "Random" as a Sort option -- when neither is selected, it should be random by default
- [x] When coming from book page, set that book filter
- [x] Restrict icons in carousel to visible area
- [x] Mobile: put-away x for lightbox should be inside lightbox
- [x] Mobile: put-away x for filter dropdowns
- [x] Mobile: lightbox scrolling issuesColor change on partner details when scroll down
- [x] Request info page stays after submitting (needs to redirect to market place)
- [Not part of FE] Request info page, > submit> ok button box can be moved and resized?
- [Content issue] Tutor and Rover have vids on dev.. But not qa? - should be fixed in staging
- [Will address later] Different fonts throughout the partner details screen
- [x] Advanced filters close box isnt pretty
- [x] Close buttons on partner details - sometimes wont work if you scroll down
- [Expected behavior] Books listed twice both get checked when you check one
- [x] Science is on the bottom of the list and cut off from it’s section
- [x] Some checkboxes aren't showing up (but the background color change is)

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
