### ISSUE TITLE
FE: Display "Verified" badge with Partner logo

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1664]
# Designs
Badge and mouseover text on Book Details sidebar: https://projects.invisionapp.com/d/main#/console/18744850/400070507/preview
Badge and mouseover text on Partners grid layout:
https://projects.invisionapp.com/d/main#/console/18744850/400070506/preview
Badge and mouseover text on Partner Details Lightbox:
https://projects.invisionapp.com/d/main#/console/18744850/400070504/preview

# Required reviews
- [ ] UX review
- [ ] Functional review

# Acceptance criteria
- [x] Badges display on the three Partner displays
- [x] Hover text displays as expected
- [x] Badges are controlled by data from the CMS

**Comment by victoria-cooke** [comment]
@RoyEJohnson Changes are available at https://trello.com/b/Vr2DfPT7/ux-review-roy-marketplace-webinars?menu=filter&filter=label:Verified%20Badges

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Testing was verified in Staging.
