### ISSUE TITLE
UX fixes for Partners lightbox

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1667]
**Fixes**
- [x] Fix distorted logos in carousel
- [x] Give Read More link its full-height space rather than floating it
- [x] Set background color for image holder (carousel)

**Review**
- [ ] UX review complete
- [ ] Dev and PDM notified about completed review

**Comment by victoria-cooke** [comment]
@RoyEJohnson I've finished looking at the review items and made some updates on Trello under the Marketplace tag.

**Comment by victoria-cooke** [comment]
@RoyEJohnson Additional fixes available on Zeplin: https://app.zeplin.io/project/5c38d00ffbb8efbdff5e6627/screen/5e556ac788f59778427d6873/
https://app.zeplin.io/project/5c38d00ffbb8efbdff5e6627/screen/5e556ac8f1689c65866e2c04/

**Comment by Brooke-Fail** [comment]
Verified this is good to go for the 2/26 release.

**Comment by Brooke-Fail** [comment]
Verified in Production.
