### ISSUE TITLE
Order a print copy doesn't handle bookstore_content of length 1

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1670]
Organizational behavior was set up with one entry in bookstore_content. The FE winds up with garbled data and gives no options. Having two entries works, but need to make it work with one.

## Testing Note
I have made Prealgebra have only one bookstore entry

# Acceptance Criteria
- [ ] "Order a print copy" under "Get the book" on the books details page displays one entry where the book is set up with one bookstore provider

**Comment by brittanyearly** [comment]
Verified on QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
