### ISSUE TITLE
Bug: Web Version Last Updated date in books 

### ISSUE THREAD

**Issue by kjdav** [openstax/os-webview#1680]
Current behavior: The Web Version Last Updated date on the book details page is pointing at Web Version Last Updated in CNX archive. 

Expected: the Web Version Last Updated date is pointing at Web Version Last Updated for the version currently in REX. Stated otherwise, the OSWeb Web Version Last Updated date should match the copyright date in the REX citation/attribution footer. 

OSweb has logic to check the book versions REX has configured, so it would be best to use that in the Web Version Last Updated date field so that our copyright dates match.

Note for Allison: The implication is that, for some books, the Web Version Last Updated date on OSweb will not exactly match the REX copyright date in the citation/attribution section (which few people are clicking). If we need help prioritizing this, we can ask Anthony, but my take is that it's minor.

## Testing note
We cannot make the necessary calls to fetch info from Rex on testing systems, so I have hard-coded the Biology information (you'll notice the TOC is always for Biology, and other Rex books will have the Web Update Date from Biology). I'm not sure what will happen on staging.

If you look at Biology 2e before this update, there is no Web Version Last Updated entry on the details page. This update adds it.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by allisonhowell** [comment]
@kjdav Just making sure you know this is going out next Wednesday.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
