### ISSUE TITLE
UX fixes

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1681]
# Description
Remaining UX fixes for Webinars, Partners, and anything else for the upcoming release can be attached here.

# Approvals
4A-UX REVIEW
- [x] Reviewed and approved by UX.

**Comment by victoria-cooke** [comment]
@RoyEJohnson The remaining fixes are up on the board: https://trello.com/b/Vr2DfPT7/ux-review-roy-marketplace-webinars

**Comment by victoria-cooke** [comment]
@RoyEJohnson This is good to go.

**Note:** Remaining fix moved to a [new card](https://app.zenhub.com/workspaces/openstax-bit-5bacfe3f4b5806bc2bea3764/issues/openstax/os-webview/1693)

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
