### ISSUE TITLE
Make Partner lightbox link text editable in the CMS

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1693]
# Description
![image.png](https://images.zenhubusercontent.com/5bacf5c2179f09585770fba9/d71ec7fa-2be2-4f09-a9bd-aea4247e6e48)

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in staging, closing.
