### ISSUE TITLE
Emergency sticky note should not care about how many times it has been displayed.

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1699]
# Description
We have an emergency sticky note which can change. Currently, if you have seen the banner 5 times, the emergency sticky note will not show up.

## Acceptance criteria
The regular sticky note still goes away after five visits.
The emergency sticky note can be dismissed, but is only dismissed for one day.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in staging, closing.
