### ISSUE TITLE
Selected books persist when you come back to adoption form

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1701]
# Description
After adopting one or more books and coming back in to do another, the original books are listed in the "how are you using" question section along with the one you intend to adopt. You can select and unselect them to clear them out.

## Acceptance Criteria
After submitting an adoption form, navigate to Subjects and select another book, choose the "Let us know" link to adopt it. When you get to the book selector, scroll down. There should only be a How are you using Book section for the new adoption, not for the already-submitted books.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
