### ISSUE TITLE
First banner image on homepage is somewhat fuzzy

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1703]
# Description
The first image in the homepage banner is lower-resolution than the other banner images and generally looks a little fuzzy.
https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/original_images/os-support-banner-desktop.png

The other images are 1937x968 and in JPG format. The first image is 1600x800 and a PNG. It may have been scaled down from its original size.

# Acceptance criteria
First banner image looks crisp

**Comment by victoria-cooke** [comment]
@allisonhowell 
Larger images attached:
[os-support-banner-desktop-3.png](https://images.zenhubusercontent.com/5c0fedb9d1fab72f0d70aeaa/23157662-e0f2-493c-b7c3-579c46806574)
[os-support-banner-mobile-3.png](https://images.zenhubusercontent.com/5c0fedb9d1fab72f0d70aeaa/015a43f3-07d4-4f22-ad39-a77c076a485b)
