### ISSUE TITLE
Allow REX to get the book slug from the CMS after the book has been "retired"

### ISSUE THREAD

**Issue by kjdav** [openstax/os-webview#1716]
Current behavior: When a book page is retired, the book name is no longer available to REX.

Desired behavior: When a book page is retired, REX can a) still call on the book name so we can generate the book urls and b) REX has some way to know the book page is retired, so we can apply different treatment to those books. 

Can BIT please work with REX to handle the cases below? The first case we will handle in REX is Psychology: we will add Psychology 2e to REX 4/22, then add Psychology 1e to REX in late May or early June.

Case 1:

GIVEN [BOOK NAME] 1e book details page is NOT available on openstax.org
WHEN the 1e book is published in REX
THEN the 1e book name in the banner displays as plain text (does not link to openstax.org)
AND the linked design is implemented on mobile and desktop

Case 2:

GIVEN [BOOK NAME] 1e is available in REX
AND the [BOOK NAME] 1e page is active on openstax.org
AND the [BOOK NAME] 2e is published in REX, also with an active 2e page on openstax.org 
WHEN the [BOOK NAME] 1e is retired on opestax.org
THEN the [BOOK NAME] 1e banner in REX displays "[BOOK NAME]" as plain text (does not link to openstax.org) 

## Implementation
We currently unpublish books to mark them as retired in the CMS. We also have a book state field, with a retired option - which actually only marks the book so it doesn't allow errata submissions.
`book_state` field to have the following options:
```
Live
Coming Soon
Deprecated
Retired
```
- Deprecated will stop errata submissions - used when books are about to be retired.
- Retired will remove it from the website but is still accessible in the API.

**Comment by kjdav** [comment]
@allisonhowell This is a new card to get the CMS to provide the book slug even after a book page is retired. this is required for us to add 1es to REX, and has become a higher priority bc of a funded commitment to publish Psych 1e by end of May and retire the book page in June. We are aiming to publish Psych 1e either May 20 or June 3, and we need to be able to handle the case where the 1e is retired sometime in June. So could you schedule this work to be ready by end of May (or so)? Let's discuss in one of the upcoming Thursday content/rex meetings. cc @TomWoodward

**Comment by TomWoodward** [comment]
for the record the endpoints we use are 
```
/apps/cms/api/v2/pages/?type=books.Book&cnx_id=031da8d3-b525-429c-80cf-6c8ed997733a
```
and
```
/apps/cms/api/v2/pages/?type=books.Book&slug=business-law-i-essentials
```

currently the data we need back from this is: `theme, slug, publish_date, authors`

we would need all that to continue working after the book page is retired

**Comment by allisonhowell** [comment]
@kjdav Gotcha. We'll get this done for the 4/22 release.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Tested in Staging, closing.
