### ISSUE TITLE
Book details page needs to handle search parameters

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1747]
# Description
The tab controls on the book details page use the entire search string. Marketing wants to be able to pass tracking parameters in the URL, so tab controls need to parse out the tab and also reassemble the search string when updating.

# Acceptance criteria
- [x] Tab preselection works with additional search string parameters
- [x] Tab changing preserves additional search string parameters
- [x] Adoption form book preselection works when additional parameters are present (but the book indicator has to come first)

## Testing notes
You can test by manually adding a parameter to the URL, for example, `https://cms-dev.openstax.org/details/books/biology-2e?something=1` (the question mark and following). Note that the default tab still loads, and you can switch between tabs, with the URL changing to keep track of the tab.

Adding parameters to the adoption form URL, for example, `https://cms-dev.openstax.org/adoption?Biology&another=something` (the & and following) should not stop it from pre-selecting the book on the second page of the form.

The same should be true for the interest form, but I need to fix that.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
