### ISSUE TITLE
Manage non-deployment-dependent settings locally

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1759]
# Description
`settings.js` contains a number of settings that do not change among the deployment environments. There is no value in having them be part of a deployment, as any change requires coordination. Those items should be kept in a separate FE settings file.

# Acceptance criteria
Only values that vary between deployment environments are in `settings.js`
Other values are managed by the FE

## Note
The settings.js file used in deployments is here: https://github.com/openstax/oscms-deployment/blob/master/templates/os-webview/src/settings.js.j2

**Comment by RoyEJohnson** [comment]
@scb6 I have updated the front end so that it only relies on `settings.js` for
```
accountHref
analyticsID
apiOrigin
mapboxPK
```

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
