### ISSUE TITLE
Port homepage to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1762]
# Description
It's good to start somewhere. Get this code out of Superb.

# Acceptance criteria
- [x] Home page is all React, with just a Superb wrapper
- [x] All tests pass

# Testing
- Regression only

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
