### ISSUE TITLE
Port About, Adopters, and Bookstore pages to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1765]
# Description
These are simple pages, just starting at the top and working my way down.

# Acceptance Criteria
- Pages work as before (regression testing only)

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Includes Contact Us form (and submission), Adoption form, Interest form, and their submissions. Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
