### ISSUE TITLE
Menu height/centering is wrong

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1771]
The main menu is somewhat clipped so that the logo is not centered and the green highlights for the menu are too low.

**Comment by victoria-cooke** [comment]
@RoyEJohnson Looks good

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
