### ISSUE TITLE
Quote buckets are laid out wrong on mobile

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1777]
# Description
The row of boxes under the banner carousel should become picture-on-top text-below on mobile. Instead, they stay left-to-right, but get an up-triangle. This is causing them to be too wide, so the whole page hangs off the right edge.

This is more obvious because they didn't used to all have pictures and the one that did fit ok.

# Acceptance Criteria
Boxes with pictures become picture-on-top text-below on phone-width screens.
The page does not extend beyond the screen

# Testing
- [x] UX only

**Comment by victoria-cooke** [comment]
@RoyEJohnson Looks great

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
