### ISSUE TITLE
Port blog page to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1782]
# Description
Part of the ongoing port from Superb to React.
The Blog page is fairly complex. It should be a fair-sized project by itself.

# Acceptance Criteria
All parts of the Blog page are implemented in React

# Acceptance Tests
Regression only

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
