### ISSUE TITLE
Port the Book Details page to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1783]
# Description
Part of the ongoing port from Superb to React
Some parts of the Book Details page have been ported to React, but some have not.

# Acceptance Criteria
All parts of the Book Details page are implemented in React
Be sure to check:
- [x] Featured resources
- [x] Video resources (on Organizational Behavior)
- [x] Locking/unlocking resources
- [x] Polish
- [x] Chevron behavior for mobile accordion groups
- [x] Accordion group automatically opens if the URL indicates it
- [x] Print links for resources
- [x] Give link in tabs and mobile
- [x] Comp copy request form (on U.S. History)
# Acceptance Tests
Regression only

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
