### ISSUE TITLE
Port Errata Form and Errata Summary to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1784]
# Description
Part of the ongoing port from Superb to React
The Errata Details page is already ported to React. Parts of the Errata Form and the Errata Summary page are still in Superb.

# Acceptance Criteria
All parts of Errata Form and Errata Summary pages are implemented in React

# Acceptance Tests
Regression only

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
