### ISSUE TITLE
Port Foundation page to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1785]
# Description
Part of the ongoing port from Superb to React

# Acceptance Criteria
- [x] All parts of the Foundation pages are implemented in React
- [x] Footer page stops importing ChildComponent (unrelated microfix)

# Acceptance Tests
Regression only

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
