### ISSUE TITLE
Port Global Reach page to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1786]
# Description
Part of the ongoing port from Superb to React.
The Global Reach page includes the interactive map.

# Acceptance Criteria
All parts of the Global Reach page are implemented in React.

# Acceptance Tests
Regression only
The URL is `/global-reach` (it's not in the menu, but is linked from the Impact page in the map section)

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
