### ISSUE TITLE
Port Impact page to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1787]
# Description
Part of the ongoing port from Superb to React.
The Impact page is a collection of small sections.

# Acceptance Criteria
All parts of the Impact are implemented in React

# Acceptance Tests
Regression only

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
