### ISSUE TITLE
Port Institutional Partnership pages to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1788]
# Description
Part of the ongoing port from Superb to React

# Acceptance Criteria
All parts of institutional-partnership and institutional-partnership-application are implemented in React.

# Acceptance Tests
Regression only

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
