### ISSUE TITLE
Port Press page to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1792]
# Description
Part of the ongoing port from Superb to React

# Acceptance Criteria
All parts of /press are implemented in React

# Acceptance Tests
Regression only
One actual change: under Press Inquiries, the telephone number and email address are links to call or email.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
