### ISSUE TITLE
Remove Quiz Results page and port Research pages to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1793]
# Description
Part of the ongoing port to React

# Acceptance Criteria
All parts of /research are implemented in React
quiz-results is gone

# Acceptance Tests
Regression only

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
