### ISSUE TITLE
Prevent multiple submissions in Renewal Popup

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1807]
# Description
Salesforce is sometimes receiving multiple duplicate submissions from the Renewal Popup form. Possibly due to multiple presses of Submit, possibly something else.
![image.png](https://images.zenhubusercontent.com/5bacf5c2179f09585770fba9/63a01726-c749-492a-9e33-e737ea298e6d)

After submitting a renewal, the submitted books should not be available to be renewed again.
The Submit button should be disabled upon submission and re-enable a few seconds later.

# Acceptance Criteria
User cannot submit the same book multiple times
User cannot do subsequent submits for a few seconds after a submit

**Comment by BruceP99166** [comment]
Check after 7/15 release.

**Comment by RoyEJohnson** [comment]
No longer seems to be happening, per Denver.
