### ISSUE TITLE
Replace IP email address across site

### ISSUE THREAD

**Issue by velcrohook02** [openstax/os-webview#1815]
We need to remove institutionalpartners@openstax.org from openstax.org and replace it with jeffdg@rice.edu.

**Locations:**
Toward the bottom of the page here: https://openstax.org/institutional-partnership

And as the College/University Partnership option address on the "What is your question about" dropdown here: https://openstax.org/contact (I think.  I don't know for sure that this sends here but needs to be checked)

If possible we should check the rest of the site too to make sure the institutionalpartners@ address doesn't live anywhere else.

**Comment by allisonhowell** [comment]
Done
