### ISSUE TITLE
Handle resource navigation on mobile

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1816]
# Description

The three-dot menu on Subjects just goes to the details page on mobile, even if the user has selected one of the resources. The selected resources section should be open.

# Note

The system uses the location search string to indicate which tab should be up on desktop. Use the same mechanism to indicate pre-opening on mobile. No need to make it two-way binding, where opening a section changes the search string.
The three-dot menus are currently disabled, but this will handle them properly.
Really need to get the release candidate fixes into master, because details pages are broken for books with a Give Today section. :(

# Acceptance tests
In mobile view, go to Subjects page. Pull down 3-dot menu for any book, choose Instructor Resources. Should go to details view with the Instructor Resources section open. (Also works for Student Resources, and for the Get This Book selection, will open the Book Details section, because that corresponds to the first tab, but that might be unexpected since the wording is Get This Book.)

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
