### ISSUE TITLE
Fix resource and menu formatting

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1832]
# Description
Production has blue squares on Student Resources boxes. Dev is making Student Resources full-width rather than gridded.
Ensure that resources are all displaying as intended.
The "Hi, User" menu is also hanging off the right edge.

# Acceptance Criteria
- [x] Student Resource boxes do not have extra ornaments
- [x] Student Resource boxes are laid out in a grid
- [x] The user menu for logged in users is right-aligned so it does not hang off the screen

# Acceptance Testing
- [x] UX Review

**Comment by RoyEJohnson** [comment]
@victoria-cooke These were some things that wrong incidental to making other changes.

**Comment by victoria-cooke** [comment]
@RoyEJohnson looks fine as far as I can tell. I did notice that the recommended popup was looking a little off, but the menu and resources seem to be ok. ![recommended popup](https://images.zenhubusercontent.com/5c0fedb9d1fab72f0d70aeaa/85573ae0-1f1b-4ce9-9b33-d94fb57109ed)

**Comment by victoria-cooke** [comment]
Confirmed with @RoyEJohnson that this is good to go. Moving to RFFV.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
