### ISSUE TITLE
Adoption and Interest form submit events are not showing up in Google Analytics

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1866]
# Description
Looks like porting the forms to React caused the submit events to no longer bubble up to the document level, where we were catching them to kick off the Google Analytics events.
Also: if you go straight to the adoption form without starting on a book page, it tries to go to the Partners page after submitting, but doesn't pass in the expected book, so gets an error.

# Acceptance criteria
- [x] Google Analytics events are sent when Adoption and Interest forms are submitted
- [x] After submitting, you are directed to the partners page with the book(s) you adopted pre-selected

# Acceptance tests
*Note* Analytics events only send when the form address is `webto.salesforce.com`. It's `test.salesforce.com` in our dev/test environments, so it will only work in Production.

**Comment by brittanyearly** [comment]
Nothing to test in QA.

**Comment by brittanyearly** [comment]
Nothing to test in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
