### ISSUE TITLE
Use CMS data for Customization Form text content

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1878]
# Description
Header, subheader, and disclaimer are now available in book data in the CMS. Use them instead of hard-coded values in the front end.

# Acceptance Criteria
Customization form for any book uses header, subheader, and disclaimer from the CMS.

# Acceptance Tests
Fields can be edited on any book page in the CMS and apply to all books.
Changes should be reflected in the form on the front end.

- [ ] UX Review

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Staging, closing.
