### ISSUE TITLE
Clicking Give Now button in microdonation banner generates error

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1882]
# Description
The microdonation banner may not have a "learn more" link. If that is missing, trying to track it breaks.

# Acceptance Criteria
Clicking "Give Now" results in a "Microdonation header give button" event even if there's no "learn more" link in the banner body.

# Acceptance Test
Set up the sticky note in the CMS so that Body has no link in it. (Dev is set up this way now).
Click the "Give today" link in the banner.
Check the Network tab for a call to "collect" that has a parameter like `ec: Microdonation%20header%20give%20button`

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging, closing.
