### ISSUE TITLE
Fix mobile menu opener

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1887]
# Description
When scrolled partway down the page, clicking the mobile menu icon scrolls you to the top of the page. You have to click again to actually open the menu.

# Acceptance criteria
Clicking the menu icon just opens the menu. Preferably without scrolling the page.

# Acceptance tests
- [ ] Menu icon works properly on mobile: load a page, go into mobile view, scroll down  the page a bit, then click to open the menu.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
