### ISSUE TITLE
Put book usage/savings blurb in mobile book details

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1891]
# Description
[Design](https://app.zeplin.io/project/5c38d00ffbb8efbdff5e6627/screen/5f05fe9af6eaea6f47d5365e)
I overlooked that there was a design for putting this blurb in the mobile version.

# Acceptance criteria
Book details pane has the same blurb as on desktop, but without the icon.

# Acceptance tests
 - [x] UX review

**Comment by victoria-cooke** [comment]
@RoyEJohnson This is good to go. cc: @brittanyearly

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
