### ISSUE TITLE
Implement FE for LLPH marketing page

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1892]
# Description
[Design](https://projects.invisionapp.com/d/main?origin=v7#/console/20636432/433739606/preview?scrollOffset=0)
Book is available only in Tutor.
Sign In button goes to Accounts and Tutor.
Page will not be linked from the menu

Accounts magic parameter will be "bri_book=LLPH"

# To be determined
- slug for page
- indicator for Accounts to markup BRI Marketing flag in Salesforce (will be attached to Login menu and orange button)

# Acceptance Tests
- [ ] UX Review

**Comment by brittanyearly** [comment]
Verified in QA. Card for Log in button functionality is https://github.com/openstax/business-intel/issues/1617.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
