### ISSUE TITLE
Fix Tech Scout analytics: most are not getting a book subject

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1893]
# Description
([From Courtney](https://openstax.slack.com/archives/C6NRD0CCQ/p1604005938444500))
I've been looking at Tech Scout analytics, and MOST of the filters have event label = N/A (rather than a book subject). Do you have any ideas why? Do you think it's possible that if someone gets there by clicking a partner lightbox from a book page, the book filter doesn't carry over into analytics?

# Acceptance Testing
The issue corrected here is that filters other than books had to be selected for an event to be generated.
 - Go to Tech Scout page, open the Network tab in the browser debugger
 - [ ] With no other filters selected, select a book. A `collect` event should be triggered.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
