### ISSUE TITLE
Ratings and Reviews UX fixes

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1899]
# Description
UX Review document:
https://docs.google.com/document/d/1nTHn-na4zjk0TNse7JWoKMyEsuvr4ajgD55iZq9CHzc/edit

# Acceptance criteria
 - [x] Stars have no outlines
 - [x] Empty stars/half-stars have default-gray background.
 - [x] Put-away X in filter lines up better with text
 - Mobile
 - [x] Fix sort menu
 - [x] Cut padding in half around/between results
 - [x] Remove padding around result count (this stops it from wrapping)
 - Lightbox
 - [x] Tabs should be sticky
 - [x] Widen lightbox
 - Overview tab
 - [x] Partner image smaller on mobile
 - Reviews tab
 - [x] Name of reviewer is bold
 - [x] Reviews list newest to oldest
 - [x] Pending message for user's review in status ???
 - [x] "You left a review" message
 - Rating/Review Form
 - [x] Tooltip text is normal black
 - [x] Rating stars have thin gray outline (this is done by overlaying scaled stars, since there's no way to do an actual outline of the stars, so the outline isn't entirely uniform)
 - [x] Text doesn't change to "Update your review" until form is submitted
 - [ ] In instructions, "guidelines" should link to guidelines page. Don't think we have one yet.
 - [x] Review textarea has helper text
 - [x] Cancel button style
 - [x] Remove PENDING from mobile view (for pending review) because it makes the Delete-Update line too long
 - [x] "Rating is required" only appears when rating is not selected; appears above buttons on mobile
 - [x] Dismiss tooltip by tapping info button again on mobile
 - [x] Less left/right padding on mobile
 - [x] Title bar (Filters - x) and button row are sticky on mobile

## Round 2
 - [x] Sort menu displays as popover menu in mobile rather than fullscreen
 - [x] Stars on rating form use SVGs with 1px outline
 - [x] Clicking Delete review triggers browser confirm dialog (delete may not work on the back end)
 - [x] Rejected review shows Rejected rather than Pending
 - [x] Pending - Update - Delete sequence wraps on mobile

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Staging, closing.
