### ISSUE TITLE
Do not show individual ratings in list of reviews (Tech Scout)

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1912]
# Description
The list of reviews includes all ratings, not just those with reviews.

# Acceptance criteria
Only actual reviews should be listed (along with their star ratings).

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Staging, closing.
