### ISSUE TITLE
Tutor marketing page webinars need a carousel

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1915]
# Description
The carousel for webinars got left out of the initial implementation.

# Acceptance criteria
See https://zpl.io/2ZZ4qk1 or ![image.png](https://images.zenhubusercontent.com/5bacf5c2179f09585770fba9/8007e360-83b2-484e-ad0b-f7fb35b82625)

# Acceptance tests
1. Webinars are in a carousel on desktop. Need more than three to get any buttons to show.
2. On mobile, it changes to a horizontal-scrolling area that shows one and a small fraction of the next one at a time.
3. Tech Scout carousel still works (I made it so they both use the same carousel widget). It does not do that switch to horizontal scrolling on mobile.
 - [ ] UX review

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Staging, closing.
