### ISSUE TITLE
Change Request -- Google Docs Customization Request Board (book field) 

### ISSUE THREAD

**Issue by Bkblodget** [openstax/os-webview#1919]
## Description

As Bey, I want the customization request board to have a book column so that I can determine for which book an instructor has requested documents. 

## Acceptance Criteria

- [ ] Given that a user has submitted a request form, when I look at the request board, then I will see the book the request was submitted for. 
![Screen Shot 2020-12-21 at 4.13.37 PM.png](https://images.zenhubusercontent.com/5b572db8a74e9a33056ecb3c/673b5d1a-0930-4d39-8063-b4a0f85c35bc)

- [ ] Given that a user has submitted a request form, when I select the request on the request board, then I will see a separate field for the book input. 

![Screen Shot 2020-12-21 at 4.13.17 PM.png](https://images.zenhubusercontent.com/5b572db8a74e9a33056ecb3c/3d1ea9be-a354-40f4-8864-fddcac3d4d58)

- [ ] Given that a user has submitted a request form, when I export the entries from the request board, then the book field will be in the export format.

**Comment by mwharrison** [comment]
@RoyEJohnson I forgot to let you know that this needed a little FE work to send the book over with the customization requests. 
You'll need to send the book id over with the request as seen in the example on the PR: https://github.com/openstax/openstax-cms/pull/1130

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
