### ISSUE TITLE
Fix `foreach` error in Analytics code

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1922]
# Description
Loading a book details page triggers an analytics code that crashes on a `foreach`.
The problem is that data keys are being camelCased now, but the code is still looking for snake_casing.

# Acceptance criteria
No more error when loading book details page.

# Acceptance tests
Book details page loads without error, and clicking the Interest form link from there works.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
