### ISSUE TITLE
Port menus to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1925]
# Description
Part of the ongoing port from Superb to React

# Acceptance criteria
The menuing system is implemented in React

# Acceptance tests
Regression only

## Note
There are lots of functional bits in the menu system, so you'll want to check that the various types of accounts get their special menu items, like "OpenStax Tutor" and "Finish signing up", as well as behavior on mobile and using key navigation.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
