### ISSUE TITLE
[FE] Updated Impact page

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1941]
# Description
[Hi-fi Zeplin](https://app.zeplin.io/project/5c38d00ffbb8efbdff5e6627/dashboard?seid=6008ca740ea2c6bd59274be1)

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
