### ISSUE TITLE
Track clicks to Google Docs Customization Form

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1942]
# Description
Leadership wants to see how many people go to the customization form to compare that against how many complete and submit it.

College Physics has a Google Docs Customization link.

# Acceptance Criteria
Clicking the customization form link generates an analytics event.
Event is 
Category: Instructor resources
Action: open
Label: Google Docs Customization

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
