### ISSUE TITLE
Errata form crashes if Tutor referral doesn't include book uuid

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1944]
# Description
 If Tutor sends you a url that lacks a book uuid like A&P it has an error [here](https://github.com/openstax/os-webview/blob/master/src/app/pages/errata-form/errata-form.js#L16)

See at [this url](https://openstax.org/errata/form?source=tutor&location=23452%401%202.1%20Elements%20and%20Atoms%3A%20The%20Building%20Blocks%20of%20Matter%20)

# Acceptance Criteria
Form handles situation where no book is included in Tutor referral

# Acceptance Tests
Use the link above, but with the testing host.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
