### ISSUE TITLE
OER Commons resource box should not include empty link

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1945]
# Description
Precalculus has no `Community Resource Feature Link` or `Community Resource Feature TText`, resulting in a red empty-link box in the OER Commons Instructor Resource.
Also College Algebra

# Acceptance Criteria
Feature links with no data should not be shown

# Acceptance Test
Precalculus or any book that doesn't have those values does not display an empty-link in the lower left of the OER Commons box.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
