### ISSUE TITLE
Change Request -- Timestamp export for Customization Requests

### ISSUE THREAD

**Issue by Bkblodget** [openstax/os-webview#1946]
## Description/User Story

As Bey, I want the timestamp field in the customization request to be included in all export formats so that I can analyze the data. 

**Related card:** https://app.zenhub.com/workspaces/openstax-bit-5bacfe3f4b5806bc2bea3764/issues/openstax/business-intel/1709

## Acceptance Criteria

- [ ] Given that a user has submitted a request form, when I export the entries from the request board, then the timestamp will be in the export format.

**Comment by mwharrison** [comment]
Issue moved to [openstax/business-intel #1747](https://github.com/openstax/business-intel/issues/1747) via [**ZenHub**](https://www.zenhub.com/)
