### ISSUE TITLE
Don't display web update date if there isn't one

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1954]
# Description
The Web Version Last Updated date in the publication info, displays `undefined Date, undefined` on LLPH, because it is not a Rex book.

# Acceptance Criteria
Web Version Last Updated only displays when there is a valid value for it. (It is currently pulled from Rex.)

# Acceptance Tests
Check LLPH and at least one book that does have a Rex `revised` value.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
