### ISSUE TITLE
Port assorted items to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1956]
# Description
Some items remain to be ported:
- [x] body units (builds articles like blog posts)
- [x] Form Select widget (actually, just remove the non-React one and the test for it)
- [x] Remove hero-journey
- [x] sticky-footer (I think just remove the non-React files)
- [x] Confirmation page imports (but does not use) componentType

Large enough to need separate cards:
- Creator Fest page
- Dialog
- general pages
- Institutional Partnership Application page

# Acceptance Criteria
These items are implemented in React and no longer reference `componentType`

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
