### ISSUE TITLE
Port Dialog widget to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1958]
# Description
Part of the ongoing port to React

# Acceptance Criteria
Dialog widget (lightbox) is implemented entirely in React

# Acceptance Tests
Regression only. Test things that use a lightbox, like partner details on Tech Scout.
College Physics Instructor Resources includes Customization Form, which brings up a lightbox
Biology 2e Instructor Resources includes iBooks Comp Copy, which brings up a lightbox
"Get this title" -> "Download the app" brings up a dialog (Biology 2e has this option)
Adoption form uses a dialog to warn you if your school doesn't match a known school name
Cookie notice is a different form of dialog (logging in in an incognito window should give you the notice)
On the Map page, Submit a testimonial brings up a dialog
Institutional Partnership participants section has a link to bring up the complete list in a lightbox
Tech Scout opens partner details in a lightbox

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
