### ISSUE TITLE
Port "general" pages to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1959]
# Description
Part of the ongoing port to React

# Acceptance Criteria
General pages are implemented entirely in React

# Acceptance Tests
Regression only. The Tech Scout review standards is a General page (it isn't on Dev, though.)
We also have /general/test-general-page

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
