### ISSUE TITLE
Port Institutional Partnership Application page to React

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1960]
# Description
Part of the ongoing port to React

# Acceptance Criteria
- [x] All parts of the Institutional Parternship Application are implemented in React
- [x] delete tab-group.js (use only tab-group.jsx)
- [x] delete content-group.js (use only content-group.jsx)

# Acceptance Tests
Regression only. URL is /institutional-partnership-application

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
