### ISSUE TITLE
Hide header/footer when printing

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1964]
# Description
When printing (for example) Terms of Service, pages after the first page get the header superimposed over the first few lines of text.

# Acceptance Criteria
Header and footer are hidden via CSS directives in printing. This will be good for blog articles as well.

# Acceptance Tests
View /tos and try printing it. In the print preview, the header and footer should not appear.
- [x] UX review

**Comment by butlerst** [comment]
UX Review: This looks good to me!

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
