### ISSUE TITLE
Opening TOC on book with four tabs encroaches on Give today link

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1967]
# Description
![image.png](https://images.zenhubusercontent.com/5bacf5c2179f09585770fba9/f75d384a-fbaf-476b-8d68-9045a9c25fa7)
On Intellectual Property, for example, in desktop mode, opening the table of contents shifts the tabs over so that the Videos tab overlays the "Give today" link.

# Acceptance criteria
"Give today" moves out of the way. (On narrower screens, the tab text wraps and fixes the problem, but that's not a correct solution, I don't think.)
Note that "Give today" is not always present. Only needs to be fixed if it is present.

# Acceptance tests
Go to a book details page with four tabs (Intellectual Property is one). Ensure that the "Give today" link is active. Open the table of contents. The link should stay out of the way of the tab labels.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
