### ISSUE TITLE
Fix pattern library accessibility issues

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1976]
# Description
Two issues were not right in the accessibility updates of #1745:
1. Blur/spread of shadow-box for buttons
2. Hover and active state colors for default buttons
The requirements are laid out on a Trello board. https://trello.com/b/YSExKQNz/cta-button-and-link-text-color-updates

# Acceptance Criteria
See Trello cards

# Acceptance Tests
- UX review only

**Comment by butlerst** [comment]
Verified in UX review.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.
