### ISSUE TITLE
Clean up old Superb code

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1988]
# Description
When the port-to-React cards are all merged, there are Superb-based widgets and such that can be removed.
- [x] Select
- [x] init-mixin
- [x] controllers/cms
- [x] cms-mixin default export, etc.
- [x] tab-group/tab
- [x] shell component needs scrubbed

# Acceptance Criteria
Regression only. Notable test items are functional things like form input widgets and tab groups, and the blog page.

**Comment by brittanyearly** [comment]
Verified in Production.
