### ISSUE TITLE
Remove Superb entirely

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1996]
# Description
The router is the last vestige of Superb in the system.

# Acceptance Criteria
- [x] Pages load
- [x] Internal links load
- [x] External links load
- [x] Give link (links with `target`) work
- [x] Subdirectory links load (errata/form)
- [x] General pages load
- [x] license, TOS, privacy, et. al., load
- [x] Tracked links are still tracked
- [x] Remove pageWrapper (and jsx-wrapper module)
- [x] Remove Superb from installed build kit
- [x] RouterBus calls to navigate are handled.

# Acceptance Tests
Regression. In particular:
- [ ] Menu links
- [ ] External links
- [ ] Give link
- [ ] Footer links
- [ ] Errata form
- [ ] Internal links within pages (like "Explore OpenStax Tech Scout" on the home page)
- [ ] Link tracking

**Comment by brittanyearly** [comment]
Link tracking is not working on QA. Two places it is working on Prod:
- Give Today links on Books
- Google Doc Customization Instructor Resource

Will update list with other expected links to be tracked.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
