### ISSUE TITLE
Optimize size of initial bundle (shake out FontAwesome)

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1998]
# Description
FontAwesome is bloating our initial JS bundle to 5.4 meg (I think 4.8M of that is FA). That's a lot to download on mobile.
In spite of constructing a library of used icons, all the icons get bundled up. Ugh.

# Approach
https://skovy.dev/tree-shaking-font-awesome/
Should be able to import the individually-used icons and webpack will shake them out.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
