### ISSUE TITLE
Revamp osweb testing system

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2007]
# Description
Tests are hard to write using Enzyme. Testing Library claims (and appears) to be a better test-writing harness.

# Acceptance Criteria
- [x] Use webpack eslint plugin
- [x] Use testing-library
- [x] Convert existing tests to use it
- [x] Fix bugs discovered by eslint
  - [x] Status is not displaying on errata detail
  - [x] Choosing an option in Order a print copy doesn't close dialog
  - [x] External links in Instructor Resources have the wrong icon

# Acceptance Tests
Regression. Note bugs in criteria list above.
This is actually included in the April 21 (22) release.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Production.
