### ISSUE TITLE
Browser tab text is "null" on subjects 

### ISSUE THREAD

**Issue by yblock** [openstax/os-webview#2015]
# Description
When browsing subject tabs at https://openstax.org/subjects the tab text is "null"

![Screen Shot 2021-04-23 at 10.32.15 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/2e990a5d-0a6b-465c-9183-66b07b282616)

# Acceptance Criteria
Browser tab always has sensible text (not "null") as the title value. It looks like fresh-loading the page works fine, but clicking on a subject category can result in null.

# Acceptance Tests
- [ ] Loading page /subjects results in browser tab title "Subjects - OpenStax"
- [ ] Loading page /subjects/math (or other category) still has title "Subjects - OpenStax"
- [ ] Clicking Math (or any other) displays the seo title for that subject (per snippets/subjects) or just "Subjects - OpenStax" (which is the subjects page title).

## Notes for fixing data:
In the CMS, the Snippet "Subjects" defines the categories that are listed, and SEO TITLE for the particular subject controls what should appear in the tab.

In Prod, those SEO TITLEs are all blank. That should get fixed. The FE fix makes it display the page title by default when the SEO TITLE is not filled in, rather than "null".

**Comment by RoyEJohnson** [comment]
snippets/subjects gives the seo_title for the subjects sub-pages. They're all blank on production.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
