### ISSUE TITLE
[FE] Homepage redesign

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2016]
# Description
[Hi fi design](https://www.figma.com/file/Mm4Bj5SNWrjWlEuFraJvGl/Faculty-Dashboard-and-Homepage?node-id=711%3A12)

# Acceptance Criteria
- [x] Links go where expected when not logged in
- [x] Links configure appropriately when logged in
- [x] Instructor/Student toggle works

# Acceptance Tests
 - [ ] UX review

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
