### ISSUE TITLE
Fix book name field in comp copy request form

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2022]
# Description
Comp copy requests were coming in without book titles because the form was using the "name" rather than the "abbreviation" from the CMS.

# Acceptance criteria
Comp copy requests come in with the book properly identified.
Example: University Physics (any volume)

**Comment by RoyEJohnson** [comment]
I have added a fix to the release candidate rc-2.80.0, scheduled for release on May 19, 2021

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
