### ISSUE TITLE
Remove Creator Fest from menu

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2027]
# Description
The last update to Creator Fest page content was for the 2020 event. There was no 2021 event. We do not have information about 2022 yet.
We can remove the menu item, and then put it back up if and when we have another CF.

# Acceptance tests

1. Creator Fest is no longer in the What We Do menu
2. Manually navigating to /creator-fest yields a bare placeholder page (that's for people who follow bookmarks or old links from somewhere else).

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
