### ISSUE TITLE
Hide webview link for Coming Soon books

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2030]
# Description
Webview links should not display for books whose status is Coming Soon. This used to work, but the way we designated Coming Soon changed.
PDF links were used for previews. That should be ok.

# Acceptance Criteria
When a book's state is Coming Soon, it has no "View online" link on the Details page.
Sociology 3e is such a book.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Staging, closing.
