### ISSUE TITLE
Remove redundant radio-button CSS

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2032]
# Description
Radio button styling is in the pattern library, but is also in the osweb codebase.
Also, the styling in the pattern library is a "real" spec, so it bloats the code every time the header file is imported.

# Acceptance Criteria
1. pattern-library makes the radio button styling a macro
2. osweb uses the pattern library macro

# Acceptance Tests
Regression only, particularly for forms with radio buttons (e.g., adoption)

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.
