### ISSUE TITLE
Add the book label for Sociology 3e when it is launched in Tutor

### ISSUE THREAD

**Issue by dkhowala** [openstax/os-webview#2047]
On the Tutor marketing page, https://openstax.org/openstax-tutor, add the book label for Sociology 3e when it is launched in Tutor. 

![Screen Shot 2021-06-22 at 9.19.35 AM.png](https://images.zenhubusercontent.com/5c12c502ea8fd844ba2fce8c/35872385-47a0-44a5-bc79-44a0cef39b6e)

**Comment by allisonhowell** [comment]
@dkhowala this is done. I took off 2e - should I leave it up?

**Comment by dkhowala** [comment]
@Allison Howell ***@***.***> Thank you. :)
I don't think we need to show 2e. The only reason we still offer it in
Tutor is that we want to phase it out gradually.
We need to add U.S. History too.
