### ISSUE TITLE
Implement Spanish language features on Subjects and Book Details pages

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2056]
# Description
This design is the addition of an icon, phrase and toggle link on certain pages, where the link will take the user to a nearly identical separate page, but with the respective content for the language. The following Hi-Fis include "FPO" notes.

## Subjects page
_Regardless of what subject is the active filter when the toggle link is clicked, the link will bring the user to the view of the page where the active filter is "View All"._
[Design View](https://www.figma.com/file/cts3vBo5i4sPiZZStAhZtf/Languages?node-id=635%3A2105)
[Presentation View](https://www.figma.com/proto/cts3vBo5i4sPiZZStAhZtf/Languages?page-id=635%3A2105&node-id=794%3A2176&viewport=-27%2C-39%2C0.2187335044145584&scaling=min-zoom)

### Need translations
- ~"About Our Textbooks" header~ use Dev Standards Header
- Hover menu items (These are "Get this book" and two tabs from the Details page)

## Book Details Page
_The toggle will be present for books with Spanish/other language equivalents. Note that there are no errata CTA buttons on Spanish books, but an email link instead._
[Design View](https://www.figma.com/file/cts3vBo5i4sPiZZStAhZtf/Languages?node-id=814%3A0)
[Presentation View](https://www.figma.com/proto/cts3vBo5i4sPiZZStAhZtf/Languages?page-id=814%3A0&node-id=814%3A315&viewport=536%2C377%2C0.22415418922901154&scaling=min-zoom)

### Need translations
- Tabs
  1. Book details (`main_tab_header` or some such)
  2. (in or associated with `free_stuff_instructor`) Instructor resources
  3. (in or associated with `free_stuff_student`) Student resources
  4. (in or associated with `videos`) Videos
- Get this title options - these should be one list that applies to all books, but they generally correspond to links on the book detail data
  1. Table of Contents
  2. View online
  3. Download the app
  4. Download a PDF
  5. Order a print copy
  6. Bookshare
  7. Download on iBooks (Part 1 and Part 2 as sub-options)
  8. Download for Kindle
  9. Chegg Reader
- "Recommended" in the Recommended callout for View Online
- Adoption and interest links ("Sign up")
  1. Sign up to <br>learn more
  2. Using this book? Let us know.
  - The tricky thing with these is they have URLs, which are different for English and Polish, and the English ones are relative links that incorporate the book title
- Author headings
  1. Senior Contributing Authors
  2. Contributing Authors
- Errata buttons
  1. Suggest a correction
  2. Errata list
  - Again tricky: errata links incorporate book title, but Polish links don't
- Publish date, et. al.
  1. Publish Date
  2. Web Version Last Updated
  3. PDF Version Last Updated
  4. Hardcover
  5. Paperback
  6. Digital
  7. iBooks/iBooks Part 1/iBooks Part 2
- CC license
  1. License
  2. by OpenStax is licensed under
- In resources:
  - Login to unlock
  - "See additional resources below"

**Book Details Page: Instructor and Student Resources tabs**
[Design View](https://www.figma.com/file/cts3vBo5i4sPiZZStAhZtf/Languages?node-id=814%3A1)
[Presentation View](https://www.figma.com/proto/cts3vBo5i4sPiZZStAhZtf/Languages?page-id=814%3A1&node-id=814%3A54&viewport=510%2C377%2C0.2165096402168274&scaling=min-zoom)

# Issues to consider
- How do we know whether a book has other language versions and what they are?
- How do we save a person's language preference? Local storage? Cookie? Always default to English and make them choose?
- Should the URL be in Spanish? subjects for English, asignaturas for Spanish? And details/books vs detalles/libros? (I'm thinking no.)

**Comment by RoyEJohnson** [comment]
@ed I've listed in the Description section the headings and such that need translations. They're generally pieces of the Book Details page. The Subjects page has a couple of items, but one is already there, and the others are really part of the Details page.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
No Spanish pages to check in Production, closing.
