### ISSUE TITLE
Language should apply to Subjects page, but not not Book Details.

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2076]
# Description
As initially written, choosing the Spanish version of the Subjects page sets your preferred language to Spanish, and in the future, going to the Subjects page will automatically bring up the Spanish translation. This is all good.

Also as written, going to a Book Details page for a book that has a Spanish translation will take you to the Spanish version if your language is set to Spanish, or to the English version if your language is set to English. And switching to the other one will change your preferred language. This is not good.

# Acceptance Criteria
- Language still controls which Subjects page you see
- Viewing the other translation of Subjects changes your default preference
- URL (not language) controls which Book Details page you see
- Viewing the other translation of a Book does _not_ change your default language preference

# Acceptance Tests
- Verify that language toggles between Spanish and English on Subjects page. Leave it on Spanish
- Verify that you can view the English translation of the Spanish book
- Verify that when you go back to Subjects after viewing the English book details, you're still on the Spanish version

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
No Spanish pages to check in Production, closing.
