### ISSUE TITLE
Subjects menu should update based on language

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2081]
# Description
The language preference controls the Subjects page, including what displays in the Subject selector bar, but the Subjects menu is always the English subjects. That won't work right.

# Acceptance Criteria
Subjects dropdown in the main menu shows the same subjects as the selector on the Subjects page.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
No Spanish pages to check in Production, closing.
