### ISSUE TITLE
Spurious Spanish translation on Tech Scout box on Instructor Resources

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2089]
# Description
On Dev, the Tech Scout box on the right of the Instructor Resources tab has its title bar in Spanish.

This could just be a matter of translating the wrong thing in the CMS. Investigate and see if it suggests any special cautions for Production

**Comment by RoyEJohnson** [comment]
Ed checked it out, and it's a straightforward mistake, not something likely to happen again.

**Comment by mwharrison** [comment]
Thanks Roy!
