### ISSUE TITLE
FE code cleanup

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2090]
# Description
A lot of the use of Contexts has been ad hoc. I now have a nice buildContext procedure, so it should be back-fitted in where Contexts are used.

# Acceptance Criteria
Everything still works, but the code is tidier

# Acceptance Tests
Regression only

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
