### ISSUE TITLE
Spanish language issues on Details page

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2102]
# Description
Per [this Slack thread](https://openstax.slack.com/archives/C69BU01RC/p1631198959077600):

1. "Get the book" is still in English
2. The webinar blurb at the bottom of Instructor Resources can't be left out or the page breaks

# Acceptance criteria
1. "Get the book" is in Spanish for Spanish books
2. If there's no webinar info in the CMS, the page still displays, but without the webinar blurb at the bottom of the Instructor Resources tab.
3. Book language changes Subjects menu language.

# Acceptance tests
(should be pretty obvious)

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Staging, closing.
