### ISSUE TITLE
PDF giving-popup-window sizing issue 

### ISSUE THREAD

**Issue by yblock** [openstax/os-webview#2107]
When downloading a PDF, the new popup window that opens after clicking to download a PDF loads the button "Go to PDF" low enough that it's cut off the page and you have to scroll to see it. 

I'm only noticing this now because I rarely use my laptop un-docked, but on a 13" macbook with the viewport at default zoom in FireFox, there's not enough screen real-estate for the popup to load within its container without needing to scroll. 

![Screen Shot 2021-09-15 at 12.35.11 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/c55ec504-0f4c-425c-a37f-3290a36e64e4)

# Acceptance Tests
Configure screen to 1024x600 (or something similar)
Go to /details/books/biology-2e
Click "Download A PDF"

The popup should appear and be fully contained in the window. Stretching the window vertically will allow the image and download icon to appear when there is enough room for them.

**Comment by butlerst** [comment]
UX Review Approved! @RoyEJohnson love what you did with the responsive resizing of this.

**Comment by allisonhowell** [comment]
Verified in Production.
