### ISSUE TITLE
Handle General Page 404s

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2109]
# Description
When a general page that doesn't exist is pulled, the site 404 page is returned, then the general page builder transfers that mess into the page, which is wrong.

Need to recognize when the data is a 404 page, and 404 as a result.

# Acceptance Criteria
Real general pages load; bogus general page URLs 404

# Acceptance Tests
- Load a real general page to confirm it works
- Load /general/does-not-exist to confirm you get a 404

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by allisonhowell** [comment]
Verified in Production.
