### ISSUE TITLE
TOC for Spanish Fisica book is broken

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2115]
# Description
On staging, [Fisica](https://staging.openstax.org/details/books/f%C3%ADsica-universitaria-volumen-1) table of contents entries all have "null" instead of a slug at the end of their URLs.

The fundamental problem is that using `/contents/<cnx-id>@<version>` is a legacy archive. It needs to pull from a refactored archive (RAP) endpoint. Tom will give better info about this on Monday.

To complicate things, in non-production environments, the contents-fetcher bypasses the fetching of information from rex and just relies on the /contents address Doing The Right Thing. That's because of CORS problems.

# Acceptance Tests
**This was included in the bugfix of Sep 28**

**Comment by brittanyearly** [comment]
Verified in Production.
