### ISSUE TITLE
Remove "Give Today" for Spanish books

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2118]
# Description
The "Give Today" link is always in English.

The text is served from https://openstax.org/apps/cms/api/give-today

# Acceptance Criteria
When the Give Today setting is active, it appears on English book details pages, but not on Spanish ones.

# Acceptance Tests
Ensure Give Today is active.
Go to Spanish book: Give Today should not appear in the row with the tabs
Flip to the English version: it should appear

**Comment by allisonhowell** [comment]
Verified in Production.
