### ISSUE TITLE
Kenetic homepage

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2121]
# Description
Per conversation with Nathan, need a homepages for Kenetic

1. Should have a top-level URL, i.e., /kenetic
2. Should load as if it were /general/kenetic

I can probably make this work as a general rule: if there is no known (in the FE) page for an address, try loading the data for the general page. If it loads, display it; otherwise, 404.

# Acceptance Criteria
When a kenetic general page exists in the CMS, loading /kenetic in osweb brings it up as if it were /general/kenetic (which will also work).

**Comment by brittanyearly** [comment]
Verified in Production on another /general page to check functionality.
