### ISSUE TITLE
New specific-subject page

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2131]
# Description
[Design](https://www.figma.com/file/lIFpeQZeCcuj9p1yLHVurT/Subjects?node-id=401%3A467)

- [x] Sticky Category siderail navigation (desktop)
- [ ] Language selector if books with translations are in the current subject
- [ ]Header text
  - Mobile sticky behavior
  - Mobile Jump to Section
    - Top level: Book Categories, Learn more
    - Lists Categories and Titles within Book Categories
    - List blog posts, webinars, our books under Learn more
- [x] Category section
  - Description
  - Book card with cover, title, and "Get the book" menu
- [x] Tutor ad (simplified for mobile)
- [ ] Blog posts about...
  - Text
  - View all button
  - Carousel
- [ ] Webinars about...
  - Text
  - View all button
  - Carousel
- [x] Learn more about accordion information panes
- [x] About textbooks info block
- [x] Three info boxes
- [x] Philanthropic support

## Data needs
- Sub-categories for each subject
```
[
    {
        name: 'Cool books',
        description: 'This is the first sub-category',
        books: firstHalf,
        id: 'cool-books'
    },
    {
        name: 'Nerd books',
        description: 'This is the other sub-category',
        books: secondHalf,
        id: 'nerd-books'
    }
]
```
- translations
- page content:
```
        introText: 'Open textbooks',
        introHtml: `
            <b>Simple to use, simple to adopt.</b> Our online business textbooks are designed
            to meet the standard scope and sequence requirements of several business
            courses – and are 100% free. Complete with free resources for educators
            (like course cartridges, PowerPoints, test banks, and more), check out our
            books to see if they&apos;re right for your course.
        `,
        blogSectionDescription: `Read up on best practices for using our free
        business textbooks and instructor resources in your course in these blog
        posts.`,
        blogSectionViewAllText: 'View all blog posts',
        blogSectionViewAllUrl: '/blog',
        blogSectionBlurbs: [
            {
                image: 'https://assets.openstax.org/oscms-prodcms/media/documents/calculus-v2.svg',
                linkText: 'Curated community resources for OpenStax business books',
                link: 'google1.com'
            },
            {
                image: 'https://assets.openstax.org/oscms-prodcms/media/documents/college_algebra.svg',
                linkText: 'What makes OpenStax Principles of Accounting unique',
                link: 'google2.com'
            },
            {
                image: 'https://assets.openstax.org/oscms-prodcms/media/original_images/AdobeStock_382934760.png',
                linkText: 'Answering your FAQs about OpenStax (Business) textbooks',
                link: 'google3.com'
            }
        ],
        learnMore: [
            {
                title: 'General Business',
                html: 'Our free introduction...'
            },
            {
                title: 'Accounting',
                html: 'Some kind of thing about accounting...'
            }
        ],
        webinarSectionDescription: `Learn how our free textbooks are made
        straight from the experts. Get tips and tricks for using an OpenStax
        book from everyday educators.`,
        webinarSectionViewAllText: 'View all webinars',
        webinarSectionViewAllUrl: '/webinars',
        webinarSectionWatchText: 'Click here to watch!',
        webinarSectionBlurbs: [
            {
                title: 'Principles of Management author webinar',
                description: `Learn about Principles of Management, our free textbook
                  for introductory management courses. This webinar covers strategies for
                  teaching with our online textbook and how you can access additional free
                  and low-cost resources.`,
                link: 'google1.com'
            },
            {
                title: 'Introduction to Business webinar',
                description: `Learn about Principles of Management, our free textbook
                  for introductory management courses. This webinar covers strategies for
                  teaching with our online textbook and how you can access additional free
                  and low-cost resources.`,
                link: 'google2.com'
            },
            {
                title: 'OpenStax Businss Ethics with author Stephen Byars',
                description: `Learn about Principles of Management, our free textbook
                  for introductory management courses. This webinar covers strategies for
                  teaching with our online textbook and how you can access additional free
                  and low-cost resources.`,
                link: 'google3.com'
            },
            {
                title: 'OpenStax Businss Ethics with author Stephen Byars',
                description: `Learn about Principles of Management, our free textbook
                  for introductory management courses. This webinar covers strategies for
                  teaching with our online textbook and how you can access additional free
                  and low-cost resources.`,
                link: 'google4.com'
            }
        ]
```

**Comment by dkhowala** [comment]
Reviewed the page on Staging. 
The page currently has placeholders for icons and images which makes it difficult to do a thorough review. 
It will be better if I do a functional review of the page when it is as close to the original as possible. 

Few things I noticed: 
- The page heading " browse our subjects" should be in sentence case. 
- Who is responsible for the final copy? some of it seems yet to be decided or is different from Sarah's design. 
- The subject order should be the same as in the design. 
- What is the logic behind the booklist order? An alphabetical order list allows for easier browsing. (This is a new request, so we can tackle it separately.) 
- Another new request, please change the font-weight of _View all...._ to bold or semibold so that users can distinguish it from other book links. 
- College success has only one book so it will not have the" view all" option. 
- In the ' instructors, take your course online' box, the spacing, and X and Y coordinates of the text are off. 
- The size of the cards is incorrect. The content is fixed to include an icon, heading, and body text. I don't see a future use case for images. 
- In the philanthropic sentence, the bold and regular text doesn't match the original design.

**Comment by dkhowala** [comment]
Hello, 

There are loads of placeholders on this page on staging which makes reviewing rather difficult. It would be more useful if I review the page at a stage as close to the original design. Let me know if you guys want to talk about this.

**Comment by brittanyearly** [comment]
Removing this from the release, as there is discussion to be had.

**Comment by brittanyearly** [comment]
Needs to be tested in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
