### ISSUE TITLE
Bugs related to Kinetic homepage

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2135]
# Description
- [ ] JS error when loading page without `general` in the path

# Acceptance Criteria
Kinetic (or kenetic on dev) page loads when URL is /kinetic or /general/kinetic. (General pages should all work this way.) In particular, JS doesn't crash, disabling menu navigation.

# Acceptance Tests
Load `/kinetic` (or any general page, but without putting /general on the front)
Page should load and all menus should function normally

**Comment by brittanyearly** [comment]
Verified in Production.
