### ISSUE TITLE
Update give banner styling

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2158]
# Description
[Updated design](https://www.figma.com/file/utT3R6QirNOjXaCsnpC83Z/Fundraising?node-id=2303%3A10)

There are two possible styles. There should be an option in the CMS to allow them to choose which way it will display.

The menu hide/show mechanism plays havoc with fixed positioning, so that will have to be addressed, making this a more complicated job than it otherwise would have been.

## Data requirement changes
1. Indicator for which display format to use
2. Thumbnail image for layout #1. Presence or absence of thumbnail could be used as format selector.
3. No headline text
```
{
  htmlMessage,
  linkText,
  linkUrl,
  image
}
```

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Staging, closing.
