### ISSUE TITLE
Limit how often fundraising dialog takes over on page load

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2160]
# Description
The fundraising dialog currently appears every time the page is fresh-loaded. It should be limited to about once a day.

# Acceptance criteria
If it has been less than 16 hours since the last display, don't show the dialog.

# Acceptance tests
Initial load of the site should display the takeover dialog
Subsequent reloads should not
If you remove the `localStorage` data item (`takeoverLoaded`), that will reset
**Note** incognito windows only preserve `localStorage` until the window is closed. So you can test that way.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by allisonhowell** [comment]
Verified in Production
