### ISSUE TITLE
Ensure pages load scrolled to the top

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2164]
# Description
When navigating between pages, sometimes scroll position is preserved. For example, on a book details page, scroll to the bottom, then navigate to the Tutor page, the content will load, but the scroll position will still be near the bottom.

# Acceptance Criteria
1. Navigating between pages by clicking links and menu items should work normally
2. When you are scrolled far down on a page and navigate to another page, the new page should be scrolled to the top

# Acceptance Tests
1. Go to a book details page (which tend to be long).
2. Scroll to near the bottom
3. Navigate to the Tutor page, or wherever
- [ ] New page should not be scrolled

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
