### ISSUE TITLE
Sentry errors in 2.90.0

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2168]
# Description

1. lower-sticky-note line 32: `buttonEl` may be undefined (this is killing tracking)
2. use getItem and setItem for localStorage.oswebLanguage to avoid problems on locked-down browsers
3. redirect /textbooks/title to /details/books/title

# Acceptance tests
As always, difficult to test tracking stuff.
1. Watch Console for errors when clicking banner
  a. put-away icon
  b. give link or button (EXCEPT: it will get an error trying to load /give locally; the proper URL should be external like https://riceconnect.rice.edu/donation/support-openstax)
2. In Safari incognito, ensure that the language selector on the Subjects page works
3. Try going to /textbooks/us-history (or some book) and note that it redirects correctly

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production. Banner is not present, but Give button caused no errors in console
