### ISSUE TITLE
[BE] Adjust homepage fields for Map and Interest (WhatsOpenStax) sections

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2194]
# Description
The updated homepage changes the links in What's OpenStax, and adds a section that links to the interactive map.

WhatsOpenStax data changes:
- No longer need give_link, give_text, learn_more_link, or learn_more_text
- Should add `interest_headline`
- I'm using `donate_text`, but it would make sense to rename it something like `interest_text`
- The link will be FE hard-coded, but the text could be `interest_link_text`

Map data:
- A block of HTML
- `button_text` (again, the link will be hard-coded in the FE)

[HiFi Design](https://www.figma.com/file/htqu82gNEO6s7xohcBQT1a/Home-%2B-Map-and-Interest-form-addition?node-id=0%3A1)

**Comment by edwoodward** [comment]
@RoyEJohnson Sample JSON attached
[https://app.zenhub.com/files/49145909/29fc7b8b-17d9-4dd9-82dc-0483d5602777/download](https://app.zenhub.com/files/49145909/29fc7b8b-17d9-4dd9-82dc-0483d5602777/download)

**Comment by RoyEJohnson** [comment]
@edwoodward That looks great!

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.
