### ISSUE TITLE
Bug: Specific-subjects page using info boxes from all-subjects page

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2207]
# Description
Per [Slack thread](https://openstax.slack.com/archives/C69BU01RC/p1651242331506859)
The three info boxes on the specific-subjects page were being populated with data from the all-subjects page. There is info box data for specific subjects in the CMS that should be used.

## Status
Fixed in release candidate

# Acceptance Criteria
Specific subjects pages (like /subjects/science) use the info box data for their subject.

**Comment by brittanyearly** [comment]
Nothing to test in QA.

**Comment by brittanyearly** [comment]
Verified in Production.
