### ISSUE TITLE
Observed issues on QA Web Week of May 17 2022

### ISSUE THREAD

**Issue by brittanyearly** [openstax/os-webview#2219]
- [ ] Homepage "About Us" link is broken

![Screen Shot 2022-05-17 at 4.34.07 PM.png](https://images.zenhubusercontent.com/5e5d63c303758d16a213e50d/f35629d9-a1b6-4f27-aef3-f8f668beb169)

- [x] Blog search bar is off-center on page, after being submitted 

![Screen Shot 2022-05-17 at 4.35.59 PM.png](https://images.zenhubusercontent.com/5e5d63c303758d16a213e50d/e64a6b4a-0d96-4f0a-a879-c747b58adb13)

- [x] Blog count exceeds number of blogs on last page 

![Screen Shot 2022-05-17 at 4.37.10 PM.png](https://images.zenhubusercontent.com/5e5d63c303758d16a213e50d/df2cf5e3-0e59-4ca2-aefa-a06d384fea33)

**Comment by RoyEJohnson** [comment]
1. Looks like the additional sections for the homepage are included in the CMS. Added to the RC.
2. Fixed
3. Also fixed
RC tag is the same: rc2.93.0, which I have deployed to Dev. Looks ok there.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
