### ISSUE TITLE
Handle translation of All Subjects and specific Subjects pages

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2226]
# Description
I could not attach my PR to the All Subjects page, so here's a new card.

# Acceptance Criteria
- All Subjects page translates between Spanish and English
- Specific Subjects pages translate between Spanish and English

## Note
On a specific subject page, the URL is used to decide the language.  There is a language selector on the page that will switch to the other translation (if one is available), and the language will be set accordingly.

The Subjects menu language selector will not change anything when you're on a specific subject page, because it just wants to change the language setting, not the URL. In the future, I may have to make the Subject menu language link aware of the current page and Do The Right Thing. But for now, it doesn't.

**Comment by DominiqueShu** [comment]
We are going to give more definition to this after B2S.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
