### ISSUE TITLE
Press Release not mobile friendly

### ISSUE THREAD

**Issue by edwoodward** [openstax/os-webview#2228]
### Description

Google sent the following notification:

Google has started validating your fix of Mobile Usability issues on your site. Specifically, we are checking for ‘Content wider than screen’, which currently affects 1 pages. 

https://openstax.org/press/48-percent-colleges-22-million-students-using-free-openstax-textbooks-year

The issue is that the images are not resizing
![image-not-resizing.png](https://images.zenhubusercontent.com/5b7b197380239d3d4d0be578/cc224fc5-4d8d-41c1-8df0-2eb23fa2c018)

### Acceptance Testing

The link above has correct size images when on a mobile device.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
