### ISSUE TITLE
Add Kinetic to Technology dropdown menu

### ISSUE THREAD

**Issue by andymuddimer** [openstax/os-webview#2232]

**Comment by andymuddimer** [comment]
Add Kinetic to Technology dropdown menu
Label: Kinetic (to be confirmed)
Link: openstax.org/kinetic/

**Comment by andymuddimer** [comment]
Label: OpenStax Kinetic

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by debshila** [comment]
@andymuddimer @daninicholson Just checking in to see where this is at and if the label has been approved. Thanks!

**Comment by andymuddimer** [comment]
I believe it will go-live on the next deployment to Production. (I am not sure when that is - maybe Wednesday?)

**Comment by debshila** [comment]
Got it, thanks!

**Comment by brittanyearly** [comment]
Verified in Production.
