### ISSUE TITLE
Footer z-index not clearing when FooterDialog is closed

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2238]
# Description
When the "We use cookies" dialog is open, the Footer gets brought to the front. It is supposed to recede when the dialog is closed.

## Recreating the problem
Use an incognito window and log in
The cookies dialog should be displayed
Go to Tech Scout page (/partners),
Select filters Type E-Reader and Cost $40+ to get no books listed.
Open the Books filter. Notice is overlaps behind the footer if the page isn't very tall.
Dismiss the dialog

The footer _should_ fall behind the filter popover.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
