### ISSUE TITLE
Blog page "Explore" sections

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2251]
# Description
[Design](https://www.figma.com/file/1LE3RFdH67GT6kmiazuHTs/Blog?node-id=942%3A634)

![image.png](https://images.zenhubusercontent.com/5bacf5c2179f09585770fba9/23f53eda-4f83-4f47-aa16-a14b7143a6ab)
![image.png](https://images.zenhubusercontent.com/5bacf5c2179f09585770fba9/a09922f9-9cdb-47e3-b9f5-bc7024b097d7)

## Notes from #2043
Subject Snippets API has images - /apps/cms/api/snippets/subjects?locale=en
Blog Collection Snippet API has title and image - /apps/cms/api/snippets/blogcollection

# Acceptance Criteria
- "Explore by subject" section appears on /blog
- "Explore collections" section appears on /blog
- Clicking a subject (e.g. the word "Math") displays page of Math-associated blog posts
- Clicking a collection name does the same for collection

## Notes
If there is only one story in a section, it will fill the available width.
Video post (on dev) has a blank image.

**Comment by mwvolo** [comment]
@DominiqueShu @ltjosephs can you verify these look as expected?

**Comment by ltjosephs** [comment]
@mwvolo thanks for working on this! a few things:

**Comment by ltjosephs** [comment]
@mwvolo thanks for working on this! a few things:

1. On dev, the order of the subjects is different than the order of the subjects on the design. Would you be able to make sure the order of the subjects is the same as in the design?
2. "Essentials" is currently one of our book disciplines. However, with the subject pages redesign, it won't be. When we redesign the subject pages, will "Essentials" be removed from the new blog page? Let me know if I need to elaborate.
3. The design has a box that reads "Interested in using OpenStax?" next to the three blog collections - can we incorporate this?

@daninicholson do you want to bring in Sarah & get her feedback?

**Comment by daninicholson** [comment]
Yes, but she will need to be brought up to speed on the project so far. Can
you do that?

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
