### ISSUE TITLE
Recognize Polish Microeconomics book

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2260]
# Description
A new book in Polish is forthcoming and needs to be recognized as such.
Title: Mikroekonomia - Podstawy
Slug: mikroekonomia-podstawy

## Solution
Add "podstawy" to the isPolish helper function keywords

# Acceptance Criteria
When you create a book with the above Title and Slug, its page behaves as a Polish book.
(Done in Dev)

**Comment by brittanyearly** [comment]
Verified in Production.
