### ISSUE TITLE
Document title for General Pages should include "OpenStax"

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2269]
# Description
In general, page titles in the CMS that don't explicitly say "OpenStax" get "- OpenStax" added to them in FE. This is not happening for General pages.

## Notes
There are two ways of setting page title. There should be one base utility that they both use.
Ensure blog, blog-explore, and general pages all set title and description as expected.

# Acceptance Criteria
A general page (or any other page) created with a Title that doesn't include "OpenStax" gets "- OpenStax" appended to it in the FE.

Page description is an entry in the <head> part of the page that looks like this:
```
<meta name="description" content="Read original content from faculty, students, OER experts, and more about a variety of topics related to OER.">
```
it is important for SEO. It is defined in the Promote tab for a page in the CMS.

**Comment by brittanyearly** [comment]
Verified in QA, using /test-page.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
