### ISSUE TITLE
Spanish book shows translation option in wrong language

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2270]
# Description
When the Language is set to English and you view a Spanish book, the translations offered are listed in English, and say "This book is available in English and English"

# Acceptance Criteria
Translations offered are based on the book language, not the Language setting (which applies to Subjects page).
Language is consistent on page: everything is Spanish for Spanish books, English for English books.
Note: Subjects menu does not display language-selector when on a Book Detail page now. That avoids the language mismatch.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
