### ISSUE TITLE
Fix MSQueue (Safari error in Sentry)

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2274]
# Description
Sentry is getting an error from Safari (only) regarding the useMSQueue function. It's not clear what the problem is, but the function is written with some bad practices, so maybe cleaning that up will fix the issue.

The issue appears to be in the use of localStorage, which is broken in Safari when incognito.

# Acceptance criteria
When multiple microsurveys (sticky microsurvey and adoption microsurvey) are available, they queue up (as before). I'm honestly unclear how to set that up in the CMS. :(
On Safari incognito window, the failure of localStorage for this is graceful (warnings in console, not errors)

**Comment by brittanyearly** [comment]
Difficult to test, will verify upon release to Production.

**Comment by brittanyearly** [comment]
This has been deployed to Production. Reopen card, or create a new one, if issue occurs.
