### ISSUE TITLE
Add text to Adoption form that versions don't matter

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2278]
# Description
We received feedback that AP Physics 1e was not an option to choose on the ‘Tell us you’re adopting’ CTA.
We should add a directive to indicate that they should choose the book by title and ignore the edition.

# Acceptance Criteria
Additional instructions along with the "Select up to" saying "Select titles you're using even if the edition is different."

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
