### ISSUE TITLE
Redirect /details to /subjects

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2280]
# Description
/details is currently a 404, and 404s get `noindex` tag so that Google doesn't put them in search results.
That may keep Google from indexing all the /details/books/title pages. So instead, we'll have /details (by itself) redirect to /subjects.

**Comment by brittanyearly** [comment]
Verified in Staging for both old and new subjects.

**Comment by brittanyearly** [comment]
Verified in Production.
