### ISSUE TITLE
Handle invalid book slug for Details page

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2284]
# Description
Going to a non-existent book details page like /details/books/notabook causes the code to go into a tight loop, making the page unresponsive. The user has to kill off the tab.

*Also* added a bit of code so that /subjects/ap reroutes to /subjects/high-school (where most unknown subjects route to view-all).

# Acceptance criteria
Invalid book slug yields a 404 page, but the website remains responsive to navigate away from it.
/subjects/ap routes to /subjects/high-school; other /subjects/notasubject route to view all.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
