### ISSUE TITLE
Fix Blog Issues

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2285]
# Description
After revising and reorganizing a lot of code, three blog bugs emerged:
1. The image at the top of the article was not displayed
2. the Gated Content blog post was in a horrible flashing loop when the user is not logged in.
3. the reading-progress ring on blog articles always shows 100% read (this is in Production already, though)

# Acceptance criteria
Blog articles display normally, including the image at the top
Gated content blog post offers the login-or-enter-information popup as expected
The reading-progress ring indicates progress

## Deployment task
Gated content form endpoint must be added to Webview Settings (Django Admin) as `gatedContentEndpoint`

**Comment by brittanyearly** [comment]
Endpoint URL `value` for Pardot is `http://go.demo.pardot.com/l/382073/2022-07-05/gxn`

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production. Gated content is not verifiable on Prod, and Pardot is down on Staging. A card for that work is created.
