### ISSUE TITLE
Fix image loading on About page, and more

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2288]
# Description
The images on the cards under "What we do" on the About page are broken in Dev, but work in Production.
Image problems also showed up on Institutional Partnership page.
There are probably some other pages where images got broken.

**ALSO**
The give microsurvey (lower-right corner popup) was not dismissing.

# Acceptance Criteria
Images load as expected
Microsurvey appears and dismisses as expected

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
