### ISSUE TITLE
Make hamburger menu keyboard-navigable

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2291]
# Description
The menu system switches to the hamburger menu at tablet size, which might include some small screen computer systems. The hamburger menu is not set up to be keyboard-navigable, which is an accessibility issue.

# Acceptance criteria
User can:
1. tab to hamburger menu
2. open it with space or enter
3. navigate through the options
4. open nested options
5. select final options

**Comment by brittanyearly** [comment]
@RoyEJohnson Can confirm this works on Safari and Chrome, but the menu did not expand on Firefox.

**Comment by mwvolo** [comment]
@andymuddimer is this a release blocker?

**Comment by RoyEJohnson** [comment]
@brittanyearly 
This is a Mac System Preferences issue.
https://support.thinkific.com/hc/en-us/articles/360060878334-Why-can-t-I-use-my-keyboard-to-move-between-links-in-Firefox-for-MacOS-

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
