### ISSUE TITLE
Add GA4 codes to staging and production

### ISSUE THREAD

**Issue by mwvolo** [openstax/os-webview#2295]
Staging code: G-0D68920QV9
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-0D68920QV9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0D68920QV9');
</script>
```

Production: G-T746F8B0QC

Note from call with Optidge: https://docs.google.com/document/d/1Kr2ck8VjPlCuFoUIlEFJACcQTRbNKhd_dTt4euH8uH4/edit

# Pre deployment task
Add entry for `GA4` to django-admin/webviewsettings

**Comment by mwvolo** [comment]
I think this needs a specific backend setting, which must be unique from other names we've used

**Comment by edwoodward** [comment]
@RoyEJohnson Added ga4ID to staging

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
