### ISSUE TITLE
Create FE page for Ally Partner Logos

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2299]
# Description
Create a new page to display Ally Partner Logos at `/ally-logos`
This replaces the separate site https://staxlogos.openstax.org/

# Prerequisites
The page data must be created in the CMS per [#1353](https://github.com/orgs/openstax/projects/14/views/9?filterQuery=assignee%3A%40me)

# Acceptance criteria
Ally logos, OpenStax logos, and Ally book cover logos are displayed and the copy buttons copy the URLs for them to the clipboard.

**Comment by brittanyearly** [comment]
Created in Staging: https://staging.openstax.org/ally-logos

**Comment by brittanyearly** [comment]
Closing, created new card.
