### ISSUE TITLE
Change K-12 Website Links

### ISSUE THREAD

**Issue by mwvolo** [openstax/os-webview#2304]
Jennifer & Andy Discussed changes to the openstax.org K-12 presence. 

- [ ] Subjects -> High School change to Subjects -> K-12

More info will be added to this card by Jennifer as she learns it -- no need to work on it until the new K-12 page is built.

## Note
This is a data change in the CMS, not tied to a release.
**Also needed**: add menu item under What We Do (text TBD)

## Implementation (things I did in Dev - Roy)
1. Snippets -> Subjects change High School to K12.
2. Clear Cloudfront Cache. This gets the old Subjects page filter and the Subjects menu working.

# Acceptance criteria
References to High School books now refer to K12 books.

- Subjects menu
- Subjects filter
- Books filter on Partners page

**Comment by RoyEJohnson** [comment]
Waiting for release of K12 page

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
