### ISSUE TITLE
Research Page

### ISSUE THREAD

**Issue by mwvolo** [openstax/os-webview#2307]
Just updating content

**Comment by iccgoncalves** [comment]
**Overview of the Task:** 
As part of Kinetic's efforts to update the OpenStax Research Page, we're requesting the BIT team to support the deployment of changes into staging and subsequently production. 

- [ ] Implementation completed in dev environment
- [ ] QA testing in dev environment
- [ ] Product Review in dev environment
- [ ] Merge PRs into staging environment
- [ ] QA testing in staging environment
- [ ] Regression Testing
- [ ] Deployment to production
- [ ] Sanity Check


https://github.com/openstax/openstax-cms/pull/1388
https://github.com/openstax/os-webview/pull/2325
