### ISSUE TITLE
Lighthouse score improvement

### ISSUE THREAD

**Issue by brittanyearly** [openstax/os-webview#2401]
Description:
Lighthouse score could use a boost in the Performance and Best Practices categories. 

Slack convo:
https://openstax.slack.com/archives/C6NRD0CCQ/p1684252207958079

Screenshot (May '23):

![Image](https://github.com/openstax/os-webview/assets/61707659/3c75408c-e9fc-4753-a739-01d43bcc722c)
![Image](https://github.com/openstax/os-webview/assets/61707659/dfe19880-7343-4d9d-aeb0-a15445485ba5)

## SEO issues
Tap targets are too small
- [x] three-dot menu on Subjects page book covers are larger
- [x] links in footer are spaced further apart on mobile
- [x] Coming Soon books don't get three-dot menu

**Comment by RoyEJohnson** [comment]
## Performance Report on Production (2.105.2) on 23 Jun 2023
Note: there is [a bug in Chrome](https://github.com/GoogleChrome/lighthouse/issues/15026#issuecomment-1591635212) that Lighthouse hangs if you have tabs in suspended/background state.
### Desktop:
Largest Contentful Paint: 2.4 s
Cumulative Layout Shift: 1.969

No specific suggestions besides image cache policy.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
