### ISSUE TITLE
Prevent creation of download resources if either the book or the contact is not set

### ISSUE THREAD

**Issue by mwvolo** [openstax/os-webview#2482]
We have started using resource downloads to build out assumed adoption information based on web activity. A pattern emerged where there are times that a resource download record is created when the salesforce id or the book id is not set. Because these are not useful for us to build records with, I propose we simply do not create them if this information is not available - saving API calls and bandwidth. 

So, do not create a resource download record if either the salesforce id or the salesforce book id is not available to be included.

[Django admin for resource downloads](https://openstax.org/django-admin/salesforce/resourcedownload/)

[Possible os-webview related code snippet](https://github.com/openstax/os-webview/blob/55d62a800c98244b138b39b83a3b250aa3594cd4/src/app/components/shell/router-helpers/useLinkHandler.ts#L56)

Please let me know if you need more clarification!

**Comment by edwoodward** [comment]
@mwvolo The contact_id is sent with a resource download along with the book name. The salesforce book id is not sent. What salesforce id are you referencing, the book id or the contact id?

**Comment by mwvolo** [comment]
@edwoodward if the book id is not sent, we receive some without a book associated with the record (so no book name). We are also receiving some without a contact_id. 

Because of our current use case of these records, we only need to be tracking verified instructors who download the PDF of the book (ideally we would capture when they click to access REX as well but that can wait). Before sending the records, we should make sure there is a contact_id in /api/user from accounts.

Hope that clears it up.

**Comment by brittanyearly** [comment]
Verified in Production.
