### ISSUE TITLE
adoption and interest forms blocked by adblockers

### ISSUE THREAD

**Issue by reedstrm** [openstax/os-webview#942]
@Aiwenar (Katalyst/OpenStax Polska developer) reported that both the adoption and interest forms are blocked by ad blockers (Ad Block Plus and Ghostery in particular) I also see this w/ Chrome and uBlock Origin.

Many many people are using ad blockers - 30-40 percent in Poland, mobile even more so.

**Comment by RoyEJohnson** [comment]
Probably refers to Katalyst's previous forms.
