### ISSUE TITLE
Clean up the dist directory

### ISSUE THREAD

**Issue by philschatz** [openstax/os-webview#986]
Running `./script/build` should generate a `./dist/` that does **not** contain the following:

- `./dist/settings.js*` : ansible should write this out as part of deployment
- `./dist/app/` : the babel-compiled JS files (but not webpack-compiled)

This is useful for deployments and tarball-generation

**Comment by meeragovindaraju** [comment]
@philschatz Is this issue still relevant?

**Comment by mwharrison** [comment]
@philschatz - I was only closing it based on talks in scrum 😃 ... @RoyEJohnson needs to determine if this is needed/how it should be done.

**Comment by RoyEJohnson** [comment]
@philschatz If I remove `dist/app`, tests fail with messages like
`Could not locate module ~/components/shell/sticky-note/sticky-note (mapped as /Users/roy/Documents/os-webview/dist/app/components/shell/sticky-note/sticky-note)`

**Comment by philschatz** [comment]
@RoyEJohnson Can you change the temporary build directory for the Gulp task that generates the `./dist/app/` directory?
